export const borderClasses = {
  borderStyle: {
    solid: "border-solid",
    dashed: "border-dashed",
    dotted: "border-dotted",
    double: "border-double",
    none: "web:border-none",
    hidden: "web:border-hidden",
  },
  borderWidth: {
    0: "border-0",
    1: "border",
    2: "border-2",
    3: "border-[3px]",
    4: "border-4",
    5: "border-[5px]",
    6: "border-[6px]",
    7: "border-[7px]",
    8: "border-8",
    9: "border-[9px]",
    10: "border-[10px]",
  },
  borderTopWidth: {
    0: "border-t-0",
    1: "border-t",
    2: "border-t-2",
    3: "border-t-[3px]",
    4: "border-t-4",
    5: "border-t-[5px]",
    6: "border-t-[6px]",
    7: "border-t-[7px]",
    8: "border-t-8",
    9: "border-t-[9px]",
    10: "border-t-[10px]",
  },
  borderBottomWidth: {
    0: "border-b-0",
    1: "border-b",
    2: "border-b-2",
    3: "border-b-[3px]",
    4: "border-b-4",
    5: "border-b-[5px]",
    6: "border-b-[6px]",
    7: "border-b-[7px]",
    8: "border-b-8",
    9: "border-b-[9px]",
    10: "border-b-[10px]",
  },
  borderLeftWidth: {
    0: "border-l-0",
    1: "border-l",
    2: "border-l-2",
    3: "border-l-[3px]",
    4: "border-l-4",
    5: "border-l-[5px]",
    6: "border-l-[6px]",
    7: "border-l-[7px]",
    8: "border-l-8",
    9: "border-l-[9px]",
    10: "border-l-[10px]",
  },
  borderRightWidth: {
    0: "border-r-0",
    1: "border-r",
    2: "border-r-2",
    3: "border-r-[3px]",
    4: "border-r-4",
    5: "border-r-[5px]",
    6: "border-r-[6px]",
    7: "border-r-[7px]",
    8: "border-r-8",
    9: "border-r-[9px]",
    10: "border-r-[10px]",
  },
  borderInlineWidth: {
    0: "border-x-0",
    1: "border-x",
    2: "border-x-2",
    3: "border-x-[3px]",
    4: "border-x-4",
    5: "border-x-[5px]",
    6: "border-x-[6px]",
    7: "border-x-[7px]",
    8: "border-x-8",
    9: "border-x-[9px]",
    10: "border-x-[10px]",
  },
  borderBlockWidth: {
    0: "border-y-0",
    1: "border-y",
    2: "border-y-2",
    3: "border-y-[3px]",
    4: "border-y-4",
    5: "border-y-[5px]",
    6: "border-y-[6px]",
    7: "border-y-[7px]",
    8: "border-y-8",
    9: "border-y-[9px]",
    10: "border-y-[10px]",
  },
};
