
export const VariantsColors = {
  "button": {
    "primary": {
      "base": "bg-primary dark:bg-dark-primary focus-visible:outline-primary dark:focus-visible:outline-dark-primary",
      "label": "text-primary-foreground dark:text-dark-primary-foreground",
      "icon": "!text-primary-foreground dark:!text-dark-primary-foreground",
      "activityIndicator": "border-t-primary-foreground dark:border-t-dark-primary-foreground"
    },
    "secondary": {
      "base": "bg-secondary dark:bg-dark-secondary focus-visible:outline-secondary dark:focus-visible:outline-dark-secondary",
      "label": "text-secondary-foreground dark:text-dark-secondary-foreground",
      "icon": "!text-secondary-foreground dark:!text-dark-secondary-foreground",
      "activityIndicator": "border-t-secondary-foreground dark:border-t-dark-secondary-foreground"
    },
    "surface": {
      "base": "bg-gray-100 dark:bg-gray-800 focus-visible:outline-gray-100 dark:focus-visible:outline-gray-800",
      "label": "text-gray-900 dark:text-gray-100",
      "icon": "!text-gray-900 dark:!text-gray-100",
      "activityIndicator": "border-t-gray-900 dark:border-t-gray-100"
    },
    "background": {
      "base": "bg-white dark:bg-gray-900 focus-visible:outline-white dark:focus-visible:outline-gray-900",
      "label": "text-gray-900 dark:text-gray-100",
      "icon": "!text-gray-900 dark:!text-gray-100",
      "activityIndicator": "border-t-gray-900 dark:border-t-gray-100"
    },
    "neutral": {
      "base": "bg-gray-500 dark:bg-gray-600 focus-visible:outline-gray-500 dark:focus-visible:outline-gray-600",
      "label": "text-white dark:text-gray-50",
      "icon": "!text-white dark:!text-gray-50",
      "activityIndicator": "border-t-white dark:border-t-gray-50"
    },
    "error": {
      "base": "bg-red-500 dark:bg-red-600 focus-visible:outline-red-500 dark:focus-visible:outline-red-600",
      "label": "text-white dark:text-red-50",
      "icon": "!text-white dark:!text-red-50",
      "activityIndicator": "border-t-white dark:border-t-red-50"
    },
    "info": {
      "base": "bg-blue-500 dark:bg-blue-600 focus-visible:outline-blue-500 dark:focus-visible:outline-blue-600",
      "label": "text-white dark:text-blue-50",
      "icon": "!text-white dark:!text-blue-50",
      "activityIndicator": "border-t-white dark:border-t-blue-50"
    },
    "warning": {
      "base": "bg-yellow-500 dark:bg-yellow-600 focus-visible:outline-yellow-500 dark:focus-visible:outline-yellow-600",
      "label": "text-yellow-900 dark:text-yellow-50",
      "icon": "!text-yellow-900 dark:!text-yellow-50",
      "activityIndicator": "border-t-yellow-900 dark:border-t-yellow-50"
    },
    "success": {
      "base": "bg-green-500 dark:bg-green-600 focus-visible:outline-green-500 dark:focus-visible:outline-green-600",
      "label": "text-white dark:text-green-50",
      "icon": "!text-white dark:!text-green-50",
      "activityIndicator": "border-t-white dark:border-t-green-50"
    },
    "text": {
      "base": "bg-gray-900 dark:bg-gray-100 focus-visible:outline-gray-900 dark:focus-visible:outline-gray-100",
      "label": "text-gray-100 dark:text-gray-900",
      "icon": "!text-gray-100 dark:!text-gray-900",
      "activityIndicator": "border-t-gray-100 dark:border-t-gray-900"
    }
  },
  "buttonOutline": {
    "primary": {
      "base": "group web:hover:bg-primary web:dark:hover:bg-dark-primary p-[5px] border-2 border-primary dark:border-dark-primary bg-transparent web:transition-[transform,color,background-color,border-color,text-decoration-color,fill,stroke]",
      "label": "web:hover:text-primary-foreground web:dark:hover:text-dark-primary-foreground web:group-hover:text-primary-foreground web:dark:group-hover:text-dark-primary-foreground text-primary dark:text-dark-primary",
      "icon": "web:hover:!text-primary-foreground web:dark:hover:!text-dark-primary-foreground web:group-hover:!text-primary-foreground web:dark:group-hover:!text-dark-primary-foreground !text-primary dark:!text-dark-primary",
      "activityIndicator": "web:hover:border-t-primary-foregund web:dark:hover:border-t-dark-primary-foreground web:group-hover:border-t-primary-foreground web:dark:group-hover:border-t-dark-primary-foreground border-t-primary dark:border-t-dark-primary"
    },
    "secondary": {
      "base": "group web:hover:bg-secondary web:dark:hover:bg-dark-secondary p-[5px] border-2 border-secondary dark:border-dark-secondary bg-transparent web:transition-[transform,color,background-color,border-color,text-decoration-color,fill,stroke]",
      "label": "web:hover:text-secondary-foreground web:dark:hover:text-dark-secondary-foreground web:group-hover:text-secondary-foreground web:dark:group-hover:text-dark-secondary-foreground text-secondary dark:text-dark-secondary",
      "icon": "web:hover:!text-secondary-foreground web:dark:hover:!text-dark-secondary-foreground web:group-hover:!text-secondary-foreground web:dark:group-hover:!text-dark-secondary-foreground !text-secondary dark:!text-dark-secondary",
      "activityIndicator": "web:hover:border-t-secondary-foregund web:dark:hover:border-t-dark-secondary-foreground web:group-hover:border-t-secondary-foreground web:dark:group-hover:border-t-dark-secondary-foreground border-t-secondary dark:border-t-dark-secondary"
    },
    "surface": {
      "base": "group web:hover:bg-gray-100 web:dark:hover:bg-gray-800 p-[5px] border-2 border-gray-100 dark:border-gray-800 bg-transparent web:transition-[transform,color,background-color,border-color,text-decoration-color,fill,stroke]",
      "label": "web:hover:text-gray-900 web:dark:hover:text-gray-100 web:group-hover:text-gray-900 web:dark:group-hover:text-gray-100 text-gray-100 dark:text-gray-800",
      "icon": "web:hover:!text-gray-900 web:dark:hover:!text-gray-100 web:group-hover:!text-gray-900 web:dark:group-hover:!text-gray-100 !text-gray-100 dark:!text-gray-800",
      "activityIndicator": "web:hover:border-t-gray-100-foregund web:dark:hover:border-t-gray-100 web:group-hover:border-t-gray-900 web:dark:group-hover:border-t-gray-100 border-t-gray-100 dark:border-t-gray-800"
    },
    "background": {
      "base": "group web:hover:bg-white web:dark:hover:bg-gray-900 p-[5px] border-2 border-white dark:border-gray-900 bg-transparent web:transition-[transform,color,background-color,border-color,text-decoration-color,fill,stroke]",
      "label": "web:hover:text-gray-900 web:dark:hover:text-gray-100 web:group-hover:text-gray-900 web:dark:group-hover:text-gray-100 text-white dark:text-gray-900",
      "icon": "web:hover:!text-gray-900 web:dark:hover:!text-gray-100 web:group-hover:!text-gray-900 web:dark:group-hover:!text-gray-100 !text-white dark:!text-gray-900",
      "activityIndicator": "web:hover:border-t-white-foregund web:dark:hover:border-t-gray-100 web:group-hover:border-t-gray-900 web:dark:group-hover:border-t-gray-100 border-t-white dark:border-t-gray-900"
    },
    "neutral": {
      "base": "group web:hover:bg-gray-500 web:dark:hover:bg-gray-600 p-[5px] border-2 border-gray-500 dark:border-gray-600 bg-transparent web:transition-[transform,color,background-color,border-color,text-decoration-color,fill,stroke]",
      "label": "web:hover:text-white web:dark:hover:text-gray-50 web:group-hover:text-white web:dark:group-hover:text-gray-50 text-gray-500 dark:text-gray-600",
      "icon": "web:hover:!text-white web:dark:hover:!text-gray-50 web:group-hover:!text-white web:dark:group-hover:!text-gray-50 !text-gray-500 dark:!text-gray-600",
      "activityIndicator": "web:hover:border-t-gray-500-foregund web:dark:hover:border-t-gray-50 web:group-hover:border-t-white web:dark:group-hover:border-t-gray-50 border-t-gray-500 dark:border-t-gray-600"
    },
    "error": {
      "base": "group web:hover:bg-red-500 web:dark:hover:bg-red-600 p-[5px] border-2 border-red-500 dark:border-red-600 bg-transparent web:transition-[transform,color,background-color,border-color,text-decoration-color,fill,stroke]",
      "label": "web:hover:text-white web:dark:hover:text-red-50 web:group-hover:text-white web:dark:group-hover:text-red-50 text-red-500 dark:text-red-600",
      "icon": "web:hover:!text-white web:dark:hover:!text-red-50 web:group-hover:!text-white web:dark:group-hover:!text-red-50 !text-red-500 dark:!text-red-600",
      "activityIndicator": "web:hover:border-t-red-500-foregund web:dark:hover:border-t-red-50 web:group-hover:border-t-white web:dark:group-hover:border-t-red-50 border-t-red-500 dark:border-t-red-600"
    },
    "info": {
      "base": "group web:hover:bg-blue-500 web:dark:hover:bg-blue-600 p-[5px] border-2 border-blue-500 dark:border-blue-600 bg-transparent web:transition-[transform,color,background-color,border-color,text-decoration-color,fill,stroke]",
      "label": "web:hover:text-white web:dark:hover:text-blue-50 web:group-hover:text-white web:dark:group-hover:text-blue-50 text-blue-500 dark:text-blue-600",
      "icon": "web:hover:!text-white web:dark:hover:!text-blue-50 web:group-hover:!text-white web:dark:group-hover:!text-blue-50 !text-blue-500 dark:!text-blue-600",
      "activityIndicator": "web:hover:border-t-blue-500-foregund web:dark:hover:border-t-blue-50 web:group-hover:border-t-white web:dark:group-hover:border-t-blue-50 border-t-blue-500 dark:border-t-blue-600"
    },
    "warning": {
      "base": "group web:hover:bg-yellow-500 web:dark:hover:bg-yellow-600 p-[5px] border-2 border-yellow-500 dark:border-yellow-600 bg-transparent web:transition-[transform,color,background-color,border-color,text-decoration-color,fill,stroke]",
      "label": "web:hover:text-yellow-900 web:dark:hover:text-yellow-50 web:group-hover:text-yellow-900 web:dark:group-hover:text-yellow-50 text-yellow-500 dark:text-yellow-600",
      "icon": "web:hover:!text-yellow-900 web:dark:hover:!text-yellow-50 web:group-hover:!text-yellow-900 web:dark:group-hover:!text-yellow-50 !text-yellow-500 dark:!text-yellow-600",
      "activityIndicator": "web:hover:border-t-yellow-500-foregund web:dark:hover:border-t-yellow-50 web:group-hover:border-t-yellow-900 web:dark:group-hover:border-t-yellow-50 border-t-yellow-500 dark:border-t-yellow-600"
    },
    "success": {
      "base": "group web:hover:bg-green-500 web:dark:hover:bg-green-600 p-[5px] border-2 border-green-500 dark:border-green-600 bg-transparent web:transition-[transform,color,background-color,border-color,text-decoration-color,fill,stroke]",
      "label": "web:hover:text-white web:dark:hover:text-green-50 web:group-hover:text-white web:dark:group-hover:text-green-50 text-green-500 dark:text-green-600",
      "icon": "web:hover:!text-white web:dark:hover:!text-green-50 web:group-hover:!text-white web:dark:group-hover:!text-green-50 !text-green-500 dark:!text-green-600",
      "activityIndicator": "web:hover:border-t-green-500-foregund web:dark:hover:border-t-green-50 web:group-hover:border-t-white web:dark:group-hover:border-t-green-50 border-t-green-500 dark:border-t-green-600"
    },
    "text": {
      "base": "group web:hover:bg-gray-900 web:dark:hover:bg-gray-100 p-[5px] border-2 border-gray-900 dark:border-gray-100 bg-transparent web:transition-[transform,color,background-color,border-color,text-decoration-color,fill,stroke]",
      "label": "web:hover:text-gray-100 web:dark:hover:text-gray-900 web:group-hover:text-gray-100 web:dark:group-hover:text-gray-900 text-gray-900 dark:text-gray-100",
      "icon": "web:hover:!text-gray-100 web:dark:hover:!text-gray-900 web:group-hover:!text-gray-100 web:dark:group-hover:!text-gray-900 !text-gray-900 dark:!text-gray-100",
      "activityIndicator": "web:hover:border-t-gray-900-foregund web:dark:hover:border-t-gray-900 web:group-hover:border-t-gray-100 web:dark:group-hover:border-t-gray-900 border-t-gray-900 dark:border-t-gray-100"
    }
  },
  "surface": {
    "primary": "bg-primary dark:bg-dark-primary text-primary-foreground dark:text-dark-primary-foreground",
    "secondary": "bg-secondary dark:bg-dark-secondary text-secondary-foreground dark:text-dark-secondary-foreground",
    "surface": "bg-gray-100 dark:bg-gray-800 text-gray-900 dark:text-gray-100",
    "background": "bg-white dark:bg-gray-900 text-gray-900 dark:text-gray-100",
    "neutral": "bg-gray-500 dark:bg-gray-600 text-white dark:text-gray-50",
    "error": "bg-red-500 dark:bg-red-600 text-white dark:text-red-50",
    "info": "bg-blue-500 dark:bg-blue-600 text-white dark:text-blue-50",
    "warning": "bg-yellow-500 dark:bg-yellow-600 text-yellow-900 dark:text-yellow-50",
    "success": "bg-green-500 dark:bg-green-600 text-white dark:text-green-50",
    "text": "bg-gray-900 dark:bg-gray-100 text-gray-100 dark:text-gray-900"
  },
  "hoverBackground": {
    "primary": "hover:bg-primary dark:bg-dark-primary",
    "secondary": "hover:bg-secondary dark:bg-dark-secondary",
    "surface": "hover:bg-gray-100 dark:bg-gray-800",
    "background": "hover:bg-white dark:bg-gray-900",
    "neutral": "hover:bg-gray-500 dark:bg-gray-600",
    "error": "hover:bg-red-500 dark:bg-red-600",
    "info": "hover:bg-blue-500 dark:bg-blue-600",
    "warning": "hover:bg-yellow-500 dark:bg-yellow-600",
    "success": "hover:bg-green-500 dark:bg-green-600",
    "text": "hover:bg-gray-900 dark:bg-gray-100"
  },
  "activeBackground": {
    "primary": "active:bg-primary dark:active:bg-dark-primary",
    "secondary": "active:bg-secondary dark:active:bg-dark-secondary",
    "surface": "active:bg-gray-100 dark:active:bg-gray-800",
    "background": "active:bg-white dark:active:bg-gray-900",
    "neutral": "active:bg-gray-500 dark:active:bg-gray-600",
    "error": "active:bg-red-500 dark:active:bg-red-600",
    "info": "active:bg-blue-500 dark:active:bg-blue-600",
    "warning": "active:bg-yellow-500 dark:active:bg-yellow-600",
    "success": "active:bg-green-500 dark:active:bg-green-600",
    "text": "active:bg-gray-900 dark:active:bg-gray-100"
  },
  "shadow": {
    "primary": "shadow-primary dark:shadow-dark-primary",
    "secondary": "shadow-secondary dark:shadow-dark-secondary",
    "surface": "shadow-gray-100 dark:shadow-gray-800",
    "background": "shadow-white dark:shadow-gray-900",
    "neutral": "shadow-gray-500 dark:shadow-gray-600",
    "error": "shadow-red-500 dark:shadow-red-600",
    "info": "shadow-blue-500 dark:shadow-blue-600",
    "warning": "shadow-yellow-500 dark:shadow-yellow-600",
    "success": "shadow-green-500 dark:shadow-green-600",
    "text": "shadow-gray-900 dark:shadow-gray-100"
  },
  "hoverShadow": {
    "primary": "hover:shadow-primary dark:hover:shadow-dark-primary",
    "secondary": "hover:shadow-secondary dark:hover:shadow-dark-secondary",
    "surface": "hover:shadow-gray-100 dark:hover:shadow-gray-800",
    "background": "hover:shadow-white dark:hover:shadow-gray-900",
    "neutral": "hover:shadow-gray-500 dark:hover:shadow-gray-600",
    "error": "hover:shadow-red-500 dark:hover:shadow-red-600",
    "info": "hover:shadow-blue-500 dark:hover:shadow-blue-600",
    "warning": "hover:shadow-yellow-500 dark:hover:shadow-yellow-600",
    "success": "hover:shadow-green-500 dark:hover:shadow-green-600",
    "text": "hover:shadow-gray-900 dark:hover:shadow-gray-100"
  },
  "activeShadow": {
    "primary": "active:shadow-primary dark:active:shadow-dark-primary",
    "secondary": "active:shadow-secondary dark:active:shadow-dark-secondary",
    "surface": "active:shadow-gray-100 dark:active:shadow-gray-800",
    "background": "active:shadow-white dark:active:shadow-gray-900",
    "neutral": "active:shadow-gray-500 dark:active:shadow-gray-600",
    "error": "active:shadow-red-500 dark:active:shadow-red-600",
    "info": "active:shadow-blue-500 dark:active:shadow-blue-600",
    "warning": "active:shadow-yellow-500 dark:active:shadow-yellow-600",
    "success": "active:shadow-green-500 dark:active:shadow-green-600",
    "text": "active:shadow-gray-900 dark:active:shadow-gray-100"
  },
  "hoverText": {
    "primary": "hover:text-primary dark:hover:text-dark-primary",
    "secondary": "hover:text-secondary dark:hover:text-dark-secondary",
    "surface": "hover:text-gray-100 dark:hover:text-gray-800",
    "background": "hover:text-white dark:hover:text-gray-900",
    "neutral": "hover:text-gray-500 dark:hover:text-gray-600",
    "error": "hover:text-red-500 dark:hover:text-red-600",
    "info": "hover:text-blue-500 dark:hover:text-blue-600",
    "warning": "hover:text-yellow-500 dark:hover:text-yellow-600",
    "success": "hover:text-green-500 dark:hover:text-green-600",
    "text": "hover:text-gray-900 dark:hover:text-gray-100",
    "primary-foreground": "hover:text-primary-foreground dark:hover:text-dark-primary-foreground",
    "secondary-foreground": "hover:text-secondary-foreground dark:hover:text-dark-secondary-foreground",
    "surface-foreground": "hover:text-gray-900 dark:hover:text-gray-100",
    "background-foreground": "hover:text-gray-900 dark:hover:text-gray-100",
    "neutral-foreground": "hover:text-white dark:hover:text-gray-50",
    "error-foreground": "hover:text-white dark:hover:text-red-50",
    "info-foreground": "hover:text-white dark:hover:text-blue-50",
    "warning-foreground": "hover:text-yellow-900 dark:hover:text-yellow-50",
    "success-foreground": "hover:text-white dark:hover:text-green-50",
    "text-foreground": "hover:text-gray-100 dark:hover:text-gray-900"
  },
  "activeText": {
    "primary": "active:text-primary dark:active:text-dark-primary",
    "secondary": "active:text-secondary dark:active:text-dark-secondary",
    "surface": "active:text-gray-100 dark:active:text-gray-800",
    "background": "active:text-white dark:active:text-gray-900",
    "neutral": "active:text-gray-500 dark:active:text-gray-600",
    "error": "active:text-red-500 dark:active:text-red-600",
    "info": "active:text-blue-500 dark:active:text-blue-600",
    "warning": "active:text-yellow-500 dark:active:text-yellow-600",
    "success": "active:text-green-500 dark:active:text-green-600",
    "text": "active:text-gray-900 dark:active:text-gray-100",
    "primary-foreground": "active:text-primary-foreground dark:active:text-dark-primary-foreground",
    "secondary-foreground": "active:text-secondary-foreground dark:active:text-dark-secondary-foreground",
    "surface-foreground": "active:text-gray-900 dark:active:text-gray-100",
    "background-foreground": "active:text-gray-900 dark:active:text-gray-100",
    "neutral-foreground": "active:text-white dark:active:text-gray-50",
    "error-foreground": "active:text-white dark:active:text-red-50",
    "info-foreground": "active:text-white dark:active:text-blue-50",
    "warning-foreground": "active:text-yellow-900 dark:active:text-yellow-50",
    "success-foreground": "active:text-white dark:active:text-green-50",
    "text-foreground": "active:text-gray-100 dark:active:text-gray-900"
  },
  "text": {
    "primary": "text-primary dark:text-dark-primary",
    "secondary": "text-secondary dark:text-dark-secondary",
    "surface": "text-gray-100 dark:text-gray-800",
    "background": "text-white dark:text-gray-900",
    "neutral": "text-gray-500 dark:text-gray-600",
    "error": "text-red-500 dark:text-red-600",
    "info": "text-blue-500 dark:text-blue-600",
    "warning": "text-yellow-500 dark:text-yellow-600",
    "success": "text-green-500 dark:text-green-600",
    "text": "text-gray-900 dark:text-gray-100",
    "primary-foreground": "text-primary-foreground dark:text-dark-primary-foreground",
    "secondary-foreground": "text-secondary-foreground dark:text-dark-secondary-foreground",
    "surface-foreground": "text-gray-900 dark:text-gray-100",
    "background-foreground": "text-gray-900 dark:text-gray-100",
    "neutral-foreground": "text-white dark:text-gray-50",
    "error-foreground": "text-white dark:text-red-50",
    "info-foreground": "text-white dark:text-blue-50",
    "warning-foreground": "text-yellow-900 dark:text-yellow-50",
    "success-foreground": "text-white dark:text-green-50",
    "text-foreground": "text-gray-100 dark:text-gray-900"
  },
  "icon": {
    "primary": "!text-primary dark:!text-dark-primary",
    "secondary": "!text-secondary dark:!text-dark-secondary",
    "surface": "!text-gray-100 dark:!text-gray-800",
    "background": "!text-white dark:!text-gray-900",
    "neutral": "!text-gray-500 dark:!text-gray-600",
    "error": "!text-red-500 dark:!text-red-600",
    "info": "!text-blue-500 dark:!text-blue-600",
    "warning": "!text-yellow-500 dark:!text-yellow-600",
    "success": "!text-green-500 dark:!text-green-600",
    "text": "!text-gray-900 dark:!text-gray-100",
    "primary-foreground": "!text-primary-foreground dark:!text-dark-primary-foreground",
    "secondary-foreground": "!text-secondary-foreground dark:!text-dark-secondary-foreground",
    "surface-foreground": "!text-gray-900 dark:!text-gray-100",
    "background-foreground": "!text-gray-900 dark:!text-gray-100",
    "neutral-foreground": "!text-white dark:!text-gray-50",
    "error-foreground": "!text-white dark:!text-red-50",
    "info-foreground": "!text-white dark:!text-blue-50",
    "warning-foreground": "!text-yellow-900 dark:!text-yellow-50",
    "success-foreground": "!text-white dark:!text-green-50",
    "text-foreground": "!text-gray-100 dark:!text-gray-900"
  },
  "hoverIcon": {
    "primary": "hover:!text-primary dark:hover:!text-dark-primary",
    "secondary": "hover:!text-secondary dark:hover:!text-dark-secondary",
    "surface": "hover:!text-gray-100 dark:hover:!text-gray-800",
    "background": "hover:!text-white dark:hover:!text-gray-900",
    "neutral": "hover:!text-gray-500 dark:hover:!text-gray-600",
    "error": "hover:!text-red-500 dark:hover:!text-red-600",
    "info": "hover:!text-blue-500 dark:hover:!text-blue-600",
    "warning": "hover:!text-yellow-500 dark:hover:!text-yellow-600",
    "success": "hover:!text-green-500 dark:hover:!text-green-600",
    "text": "hover:!text-gray-900 dark:hover:!text-gray-100",
    "primary-foreground": "hover:!text-primary-foreground dark:hover:!text-dark-primary-foreground",
    "secondary-foreground": "hover:!text-secondary-foreground dark:hover:!text-dark-secondary-foreground",
    "surface-foreground": "hover:!text-gray-900 dark:hover:!text-gray-100",
    "background-foreground": "hover:!text-gray-900 dark:hover:!text-gray-100",
    "neutral-foreground": "hover:!text-white dark:hover:!text-gray-50",
    "error-foreground": "hover:!text-white dark:hover:!text-red-50",
    "info-foreground": "hover:!text-white dark:hover:!text-blue-50",
    "warning-foreground": "hover:!text-yellow-900 dark:hover:!text-yellow-50",
    "success-foreground": "hover:!text-white dark:hover:!text-green-50",
    "text-foreground": "hover:!text-gray-100 dark:hover:!text-gray-900"
  },
  "activeIcon": {
    "primary": "active:!text-primary dark:active:!text-dark-primary",
    "secondary": "active:!text-secondary dark:active:!text-dark-secondary",
    "surface": "active:!text-gray-100 dark:active:!text-gray-800",
    "background": "active:!text-white dark:active:!text-gray-900",
    "neutral": "active:!text-gray-500 dark:active:!text-gray-600",
    "error": "active:!text-red-500 dark:active:!text-red-600",
    "info": "active:!text-blue-500 dark:active:!text-blue-600",
    "warning": "active:!text-yellow-500 dark:active:!text-yellow-600",
    "success": "active:!text-green-500 dark:active:!text-green-600",
    "text": "active:!text-gray-900 dark:active:!text-gray-100",
    "primary-foreground": "active:!text-primary-foreground dark:active:!text-dark-primary-foreground",
    "secondary-foreground": "active:!text-secondary-foreground dark:active:!text-dark-secondary-foreground",
    "surface-foreground": "active:!text-gray-900 dark:active:!text-gray-100",
    "background-foreground": "active:!text-gray-900 dark:active:!text-gray-100",
    "neutral-foreground": "active:!text-white dark:active:!text-gray-50",
    "error-foreground": "active:!text-white dark:active:!text-red-50",
    "info-foreground": "active:!text-white dark:active:!text-blue-50",
    "warning-foreground": "active:!text-yellow-900 dark:active:!text-yellow-50",
    "success-foreground": "active:!text-white dark:active:!text-green-50",
    "text-foreground": "active:!text-gray-100 dark:active:!text-gray-900"
  },
  "background": {
    "primary": "bg-primary dark:bg-dark-primary",
    "secondary": "bg-secondary dark:bg-dark-secondary",
    "surface": "bg-gray-100 dark:bg-gray-800",
    "background": "bg-white dark:bg-gray-900",
    "neutral": "bg-gray-500 dark:bg-gray-600",
    "error": "bg-red-500 dark:bg-red-600",
    "info": "bg-blue-500 dark:bg-blue-600",
    "warning": "bg-yellow-500 dark:bg-yellow-600",
    "success": "bg-green-500 dark:bg-green-600",
    "text": "bg-gray-900 dark:bg-gray-100"
  },
  "textForeground": {
    "primary-foreground": "text-primary-foreground dark:text-dark-primary-foreground",
    "secondary-foreground": "text-secondary-foreground dark:text-dark-secondary-foreground",
    "surface-foreground": "text-gray-900 dark:text-gray-100",
    "background-foreground": "text-gray-900 dark:text-gray-100",
    "neutral-foreground": "text-white dark:text-gray-50",
    "error-foreground": "text-white dark:text-red-50",
    "info-foreground": "text-white dark:text-blue-50",
    "warning-foreground": "text-yellow-900 dark:text-yellow-50",
    "success-foreground": "text-white dark:text-green-50",
    "text-foreground": "text-gray-100 dark:text-gray-900"
  },
  "hoverTextForeground": {
    "primary-foreground": "hover:text-primary-foreground dark:hover:text-dark-primary-foreground",
    "secondary-foreground": "hover:text-secondary-foreground dark:hover:text-dark-secondary-foreground",
    "surface-foreground": "hover:text-gray-900 dark:hover:text-gray-100",
    "background-foreground": "hover:text-gray-900 dark:hover:text-gray-100",
    "neutral-foreground": "hover:text-white dark:hover:text-gray-50",
    "error-foreground": "hover:text-white dark:hover:text-red-50",
    "info-foreground": "hover:text-white dark:hover:text-blue-50",
    "warning-foreground": "hover:text-yellow-900 dark:hover:text-yellow-50",
    "success-foreground": "hover:text-white dark:hover:text-green-50",
    "text-foreground": "hover:text-gray-100 dark:hover:text-gray-900"
  },
  "activeTextForeground": {
    "primary-foreground": "active:text-primary-foreground dark:active:text-dark-primary-foreground",
    "secondary-foreground": "active:text-secondary-foreground dark:active:text-dark-secondary-foreground",
    "surface-foreground": "active:text-gray-900 dark:active:text-gray-100",
    "background-foreground": "active:text-gray-900 dark:active:text-gray-100",
    "neutral-foreground": "active:text-white dark:active:text-gray-50",
    "error-foreground": "active:text-white dark:active:text-red-50",
    "info-foreground": "active:text-white dark:active:text-blue-50",
    "warning-foreground": "active:text-yellow-900 dark:active:text-yellow-50",
    "success-foreground": "active:text-white dark:active:text-green-50",
    "text-foreground": "active:text-gray-100 dark:active:text-gray-900"
  },
  "iconForeground": {
    "primary-foreground": "!text-primary-foreground dark:!text-dark-primary-foreground",
    "secondary-foreground": "!text-secondary-foreground dark:!text-dark-secondary-foreground",
    "surface-foreground": "!text-gray-900 dark:!text-gray-100",
    "background-foreground": "!text-gray-900 dark:!text-gray-100",
    "neutral-foreground": "!text-white dark:!text-gray-50",
    "error-foreground": "!text-white dark:!text-red-50",
    "info-foreground": "!text-white dark:!text-blue-50",
    "warning-foreground": "!text-yellow-900 dark:!text-yellow-50",
    "success-foreground": "!text-white dark:!text-green-50",
    "text-foreground": "!text-gray-100 dark:!text-gray-900"
  },
  "hoverIconForeground": {
    "primary-foreground": "hover:!text-primary-foreground dark:hover:!text-dark-primary-foreground",
    "secondary-foreground": "hover:!text-secondary-foreground dark:hover:!text-dark-secondary-foreground",
    "surface-foreground": "hover:!text-gray-900 dark:hover:!text-gray-100",
    "background-foreground": "hover:!text-gray-900 dark:hover:!text-gray-100",
    "neutral-foreground": "hover:!text-white dark:hover:!text-gray-50",
    "error-foreground": "hover:!text-white dark:hover:!text-red-50",
    "info-foreground": "hover:!text-white dark:hover:!text-blue-50",
    "warning-foreground": "hover:!text-yellow-900 dark:hover:!text-yellow-50",
    "success-foreground": "hover:!text-white dark:hover:!text-green-50",
    "text-foreground": "hover:!text-gray-100 dark:hover:!text-gray-900"
  },
  "activeIconForeground": {
    "primary-foreground": "active:!text-primary-foreground dark:active:!text-dark-primary-foreground",
    "secondary-foreground": "active:!text-secondary-foreground dark:active:!text-dark-secondary-foreground",
    "surface-foreground": "active:!text-gray-900 dark:active:!text-gray-100",
    "background-foreground": "active:!text-gray-900 dark:active:!text-gray-100",
    "neutral-foreground": "active:!text-white dark:active:!text-gray-50",
    "error-foreground": "active:!text-white dark:active:!text-red-50",
    "info-foreground": "active:!text-white dark:active:!text-blue-50",
    "warning-foreground": "active:!text-yellow-900 dark:active:!text-yellow-50",
    "success-foreground": "active:!text-white dark:active:!text-green-50",
    "text-foreground": "active:!text-gray-100 dark:active:!text-gray-900"
  },
  "borderColor": {
    "primary": "border-primary dark:border-dark-primary",
    "secondary": "border-secondary dark:border-dark-secondary",
    "surface": "border-gray-100 dark:border-gray-800",
    "background": "border-white dark:border-gray-900",
    "neutral": "border-gray-500 dark:border-gray-600",
    "error": "border-red-500 dark:border-red-600",
    "info": "border-blue-500 dark:border-blue-600",
    "warning": "border-yellow-500 dark:border-yellow-600",
    "success": "border-green-500 dark:border-green-600",
    "text": "border-gray-900 dark:border-gray-100",
    "primary-foreground": "border-primary-foreground dark:border-dark-primary-foreground",
    "secondary-foreground": "border-secondary-foreground dark:border-dark-secondary-foreground",
    "surface-foreground": "border-gray-900 dark:border-gray-100",
    "background-foreground": "border-gray-900 dark:border-gray-100",
    "neutral-foreground": "border-white dark:border-gray-50",
    "error-foreground": "border-white dark:border-red-50",
    "info-foreground": "border-white dark:border-blue-50",
    "warning-foreground": "border-yellow-900 dark:border-yellow-50",
    "success-foreground": "border-white dark:border-green-50",
    "text-foreground": "border-gray-100 dark:border-gray-900"
  },
  "borderTopColor": {
    "primary": "border-t-primary dark:border-t-dark-primary",
    "secondary": "border-t-secondary dark:border-t-dark-secondary",
    "surface": "border-t-gray-100 dark:border-t-gray-800",
    "background": "border-t-white dark:border-t-gray-900",
    "neutral": "border-t-gray-500 dark:border-t-gray-600",
    "error": "border-t-red-500 dark:border-t-red-600",
    "info": "border-t-blue-500 dark:border-t-blue-600",
    "warning": "border-t-yellow-500 dark:border-t-yellow-600",
    "success": "border-t-green-500 dark:border-t-green-600",
    "text": "border-t-gray-900 dark:border-t-gray-100",
    "primary-foreground": "border-t-primary-foreground dark:border-t-dark-primary-foreground",
    "secondary-foreground": "border-t-secondary-foreground dark:border-t-dark-secondary-foreground",
    "surface-foreground": "border-t-gray-900 dark:border-t-gray-100",
    "background-foreground": "border-t-gray-900 dark:border-t-gray-100",
    "neutral-foreground": "border-t-white dark:border-t-gray-50",
    "error-foreground": "border-t-white dark:border-t-red-50",
    "info-foreground": "border-t-white dark:border-t-blue-50",
    "warning-foreground": "border-t-yellow-900 dark:border-t-yellow-50",
    "success-foreground": "border-t-white dark:border-t-green-50",
    "text-foreground": "border-t-gray-100 dark:border-t-gray-900"
  },
  "borderBottomColor": {
    "primary": "border-b-primary dark:border-b-dark-primary",
    "secondary": "border-b-secondary dark:border-b-dark-secondary",
    "surface": "border-b-gray-100 dark:border-b-gray-800",
    "background": "border-b-white dark:border-b-gray-900",
    "neutral": "border-b-gray-500 dark:border-b-gray-600",
    "error": "border-b-red-500 dark:border-b-red-600",
    "info": "border-b-blue-500 dark:border-b-blue-600",
    "warning": "border-b-yellow-500 dark:border-b-yellow-600",
    "success": "border-b-green-500 dark:border-b-green-600",
    "text": "border-b-gray-900 dark:border-b-gray-100",
    "primary-foreground": "border-b-primary-foreground dark:border-b-dark-primary-foreground",
    "secondary-foreground": "border-b-secondary-foreground dark:border-b-dark-secondary-foreground",
    "surface-foreground": "border-b-gray-900 dark:border-b-gray-100",
    "background-foreground": "border-b-gray-900 dark:border-b-gray-100",
    "neutral-foreground": "border-b-white dark:border-b-gray-50",
    "error-foreground": "border-b-white dark:border-b-red-50",
    "info-foreground": "border-b-white dark:border-b-blue-50",
    "warning-foreground": "border-b-yellow-900 dark:border-b-yellow-50",
    "success-foreground": "border-b-white dark:border-b-green-50",
    "text-foreground": "border-b-gray-100 dark:border-b-gray-900"
  },
  "borderLeftColor": {
    "primary": "border-l-primary dark:border-l-dark-primary",
    "secondary": "border-l-secondary dark:border-l-dark-secondary",
    "surface": "border-l-gray-100 dark:border-l-gray-800",
    "background": "border-l-white dark:border-l-gray-900",
    "neutral": "border-l-gray-500 dark:border-l-gray-600",
    "error": "border-l-red-500 dark:border-l-red-600",
    "info": "border-l-blue-500 dark:border-l-blue-600",
    "warning": "border-l-yellow-500 dark:border-l-yellow-600",
    "success": "border-l-green-500 dark:border-l-green-600",
    "text": "border-l-gray-900 dark:border-l-gray-100",
    "primary-foreground": "border-l-primary-foreground dark:border-l-dark-primary-foreground",
    "secondary-foreground": "border-l-secondary-foreground dark:border-l-dark-secondary-foreground",
    "surface-foreground": "border-l-gray-900 dark:border-l-gray-100",
    "background-foreground": "border-l-gray-900 dark:border-l-gray-100",
    "neutral-foreground": "border-l-white dark:border-l-gray-50",
    "error-foreground": "border-l-white dark:border-l-red-50",
    "info-foreground": "border-l-white dark:border-l-blue-50",
    "warning-foreground": "border-l-yellow-900 dark:border-l-yellow-50",
    "success-foreground": "border-l-white dark:border-l-green-50",
    "text-foreground": "border-l-gray-100 dark:border-l-gray-900"
  },
  "borderRightColor": {
    "primary": "border-r-primary dark:border-r-dark-primary",
    "secondary": "border-r-secondary dark:border-r-dark-secondary",
    "surface": "border-r-gray-100 dark:border-r-gray-800",
    "background": "border-r-white dark:border-r-gray-900",
    "neutral": "border-r-gray-500 dark:border-r-gray-600",
    "error": "border-r-red-500 dark:border-r-red-600",
    "info": "border-r-blue-500 dark:border-r-blue-600",
    "warning": "border-r-yellow-500 dark:border-r-yellow-600",
    "success": "border-r-green-500 dark:border-r-green-600",
    "text": "border-r-gray-900 dark:border-r-gray-100",
    "primary-foreground": "border-r-primary-foreground dark:border-r-dark-primary-foreground",
    "secondary-foreground": "border-r-secondary-foreground dark:border-r-dark-secondary-foreground",
    "surface-foreground": "border-r-gray-900 dark:border-r-gray-100",
    "background-foreground": "border-r-gray-900 dark:border-r-gray-100",
    "neutral-foreground": "border-r-white dark:border-r-gray-50",
    "error-foreground": "border-r-white dark:border-r-red-50",
    "info-foreground": "border-r-white dark:border-r-blue-50",
    "warning-foreground": "border-r-yellow-900 dark:border-r-yellow-50",
    "success-foreground": "border-r-white dark:border-r-green-50",
    "text-foreground": "border-r-gray-100 dark:border-r-gray-900"
  },
  "activityIndicator": {
    "primary": "border-t-primary dark:border-t-dark-primary",
    "secondary": "border-t-secondary dark:border-t-dark-secondary",
    "surface": "border-t-gray-100 dark:border-t-gray-800",
    "background": "border-t-white dark:border-t-gray-900",
    "neutral": "border-t-gray-500 dark:border-t-gray-600",
    "error": "border-t-red-500 dark:border-t-red-600",
    "info": "border-t-blue-500 dark:border-t-blue-600",
    "warning": "border-t-yellow-500 dark:border-t-yellow-600",
    "success": "border-t-green-500 dark:border-t-green-600",
    "text": "border-t-gray-900 dark:border-t-gray-100",
    "primary-foreground": "border-t-primary-foreground dark:border-t-dark-primary-foreground",
    "secondary-foreground": "border-t-secondary-foreground dark:border-t-dark-secondary-foreground",
    "surface-foreground": "border-t-gray-900 dark:border-t-gray-100",
    "background-foreground": "border-t-gray-900 dark:border-t-gray-100",
    "neutral-foreground": "border-t-white dark:border-t-gray-50",
    "error-foreground": "border-t-white dark:border-t-red-50",
    "info-foreground": "border-t-white dark:border-t-blue-50",
    "warning-foreground": "border-t-yellow-900 dark:border-t-yellow-50",
    "success-foreground": "border-t-white dark:border-t-green-50",
    "text-foreground": "border-t-gray-100 dark:border-t-gray-900"
  },
  "ringColors": {
    "primary": "ring-primary dark:ring-dark-primary",
    "secondary": "ring-secondary dark:ring-dark-secondary",
    "surface": "ring-gray-100 dark:ring-gray-800",
    "background": "ring-white dark:ring-gray-900",
    "neutral": "ring-gray-500 dark:ring-gray-600",
    "error": "ring-red-500 dark:ring-red-600",
    "info": "ring-blue-500 dark:ring-blue-600",
    "warning": "ring-yellow-500 dark:ring-yellow-600",
    "success": "ring-green-500 dark:ring-green-600",
    "text": "ring-gray-900 dark:ring-gray-100",
    "primary-foreground": "ring-primary-foreground dark:ring-dark-primary-foreground",
    "secondary-foreground": "ring-secondary-foreground dark:ring-dark-secondary-foreground",
    "surface-foreground": "ring-gray-900 dark:ring-gray-100",
    "background-foreground": "ring-gray-900 dark:ring-gray-100",
    "neutral-foreground": "ring-white dark:ring-gray-50",
    "error-foreground": "ring-white dark:ring-red-50",
    "info-foreground": "ring-white dark:ring-blue-50",
    "warning-foreground": "ring-yellow-900 dark:ring-yellow-50",
    "success-foreground": "ring-white dark:ring-green-50",
    "text-foreground": "ring-gray-100 dark:ring-gray-900"
  },
  "hoverRingColors": {
    "primary": "hover:ring-primary dark:hover:ring-dark-primary",
    "secondary": "hover:ring-secondary dark:hover:ring-dark-secondary",
    "surface": "hover:ring-gray-100 dark:hover:ring-gray-800",
    "background": "hover:ring-white dark:hover:ring-gray-900",
    "neutral": "hover:ring-gray-500 dark:hover:ring-gray-600",
    "error": "hover:ring-red-500 dark:hover:ring-red-600",
    "info": "hover:ring-blue-500 dark:hover:ring-blue-600",
    "warning": "hover:ring-yellow-500 dark:hover:ring-yellow-600",
    "success": "hover:ring-green-500 dark:hover:ring-green-600",
    "text": "hover:ring-gray-900 dark:hover:ring-gray-100",
    "primary-foreground": "hover:ring-primary-foreground dark:hover:ring-dark-primary-foreground",
    "secondary-foreground": "hover:ring-secondary-foreground dark:hover:ring-dark-secondary-foreground",
    "surface-foreground": "hover:ring-gray-900 dark:hover:ring-gray-100",
    "background-foreground": "hover:ring-gray-900 dark:hover:ring-gray-100",
    "neutral-foreground": "hover:ring-white dark:hover:ring-gray-50",
    "error-foreground": "hover:ring-white dark:hover:ring-red-50",
    "info-foreground": "hover:ring-white dark:hover:ring-blue-50",
    "warning-foreground": "hover:ring-yellow-900 dark:hover:ring-yellow-50",
    "success-foreground": "hover:ring-white dark:hover:ring-green-50",
    "text-foreground": "hover:ring-gray-100 dark:hover:ring-gray-900"
  },
  "activeRingColors": {
    "primary": "active:ring-primary dark:active:ring-dark-primary",
    "secondary": "active:ring-secondary dark:active:ring-dark-secondary",
    "surface": "active:ring-gray-100 dark:active:ring-gray-800",
    "background": "active:ring-white dark:active:ring-gray-900",
    "neutral": "active:ring-gray-500 dark:active:ring-gray-600",
    "error": "active:ring-red-500 dark:active:ring-red-600",
    "info": "active:ring-blue-500 dark:active:ring-blue-600",
    "warning": "active:ring-yellow-500 dark:active:ring-yellow-600",
    "success": "active:ring-green-500 dark:active:ring-green-600",
    "text": "active:ring-gray-900 dark:active:ring-gray-100",
    "primary-foreground": "active:ring-primary-foreground dark:active:ring-dark-primary-foreground",
    "secondary-foreground": "active:ring-secondary-foreground dark:active:ring-dark-secondary-foreground",
    "surface-foreground": "active:ring-gray-900 dark:active:ring-gray-100",
    "background-foreground": "active:ring-gray-900 dark:active:ring-gray-100",
    "neutral-foreground": "active:ring-white dark:active:ring-gray-50",
    "error-foreground": "active:ring-white dark:active:ring-red-50",
    "info-foreground": "active:ring-white dark:active:ring-blue-50",
    "warning-foreground": "active:ring-yellow-900 dark:active:ring-yellow-50",
    "success-foreground": "active:ring-white dark:active:ring-green-50",
    "text-foreground": "active:ring-gray-100 dark:active:ring-gray-900"
  },
  "focusRingColors": {
    "primary": "focus:ring-primary dark:focus:ring-dark-primary",
    "secondary": "focus:ring-secondary dark:focus:ring-dark-secondary",
    "surface": "focus:ring-gray-100 dark:focus:ring-gray-800",
    "background": "focus:ring-white dark:focus:ring-gray-900",
    "neutral": "focus:ring-gray-500 dark:focus:ring-gray-600",
    "error": "focus:ring-red-500 dark:focus:ring-red-600",
    "info": "focus:ring-blue-500 dark:focus:ring-blue-600",
    "warning": "focus:ring-yellow-500 dark:focus:ring-yellow-600",
    "success": "focus:ring-green-500 dark:focus:ring-green-600",
    "text": "focus:ring-gray-900 dark:focus:ring-gray-100",
    "primary-foreground": "focus:ring-primary-foreground dark:focus:ring-dark-primary-foreground",
    "secondary-foreground": "focus:ring-secondary-foreground dark:focus:ring-dark-secondary-foreground",
    "surface-foreground": "focus:ring-gray-900 dark:focus:ring-gray-100",
    "background-foreground": "focus:ring-gray-900 dark:focus:ring-gray-100",
    "neutral-foreground": "focus:ring-white dark:focus:ring-gray-50",
    "error-foreground": "focus:ring-white dark:focus:ring-red-50",
    "info-foreground": "focus:ring-white dark:focus:ring-blue-50",
    "warning-foreground": "focus:ring-yellow-900 dark:focus:ring-yellow-50",
    "success-foreground": "focus:ring-white dark:focus:ring-green-50",
    "text-foreground": "focus:ring-gray-100 dark:focus:ring-gray-900"
  },
  "allColors": {}
}
    