
export const VariantsColors = {
  "button": {
    "primary": {
      "base": "bg-primary dark:bg-dark-primary focus-visible:outline-primary dark:focus-visible:outline-dark-primary",
      "label": "text-primary-foreground dark:text-dark-primary-foreground",
      "icon": "!text-primary-foreground dark:!text-dark-primary-foreground",
      "activityIndicator": "bg-primary-foreground dark:bg-dark-primary-foreground"
    },
    "secondary": {
      "base": "bg-secondary dark:bg-dark-secondary focus-visible:outline-secondary dark:focus-visible:outline-dark-secondary",
      "label": "text-secondary-foreground dark:text-dark-secondary-foreground",
      "icon": "!text-secondary-foreground dark:!text-dark-secondary-foreground",
      "activityIndicator": "bg-secondary-foreground dark:bg-dark-secondary-foreground"
    },
    "surface": {
      "base": "bg-gray-100 dark:bg-gray-800 focus-visible:outline-gray-100 dark:focus-visible:outline-gray-800",
      "label": "text-gray-900 dark:text-gray-100",
      "icon": "!text-gray-900 dark:!text-gray-100",
      "activityIndicator": "bg-gray-900 dark:bg-gray-100"
    },
    "background": {
      "base": "bg-white dark:bg-gray-900 focus-visible:outline-white dark:focus-visible:outline-gray-900",
      "label": "text-gray-900 dark:text-gray-100",
      "icon": "!text-gray-900 dark:!text-gray-100",
      "activityIndicator": "bg-gray-900 dark:bg-gray-100"
    },
    "neutral": {
      "base": "bg-gray-500 dark:bg-gray-600 focus-visible:outline-gray-500 dark:focus-visible:outline-gray-600",
      "label": "text-white dark:text-gray-50",
      "icon": "!text-white dark:!text-gray-50",
      "activityIndicator": "bg-white dark:bg-gray-50"
    },
    "error": {
      "base": "bg-red-500 dark:bg-red-600 focus-visible:outline-red-500 dark:focus-visible:outline-red-600",
      "label": "text-white dark:text-red-50",
      "icon": "!text-white dark:!text-red-50",
      "activityIndicator": "bg-white dark:bg-red-50"
    },
    "info": {
      "base": "bg-blue-500 dark:bg-blue-600 focus-visible:outline-blue-500 dark:focus-visible:outline-blue-600",
      "label": "text-white dark:text-blue-50",
      "icon": "!text-white dark:!text-blue-50",
      "activityIndicator": "bg-white dark:bg-blue-50"
    },
    "warning": {
      "base": "bg-yellow-500 dark:bg-yellow-600 focus-visible:outline-yellow-500 dark:focus-visible:outline-yellow-600",
      "label": "text-yellow-900 dark:text-yellow-50",
      "icon": "!text-yellow-900 dark:!text-yellow-50",
      "activityIndicator": "bg-yellow-900 dark:bg-yellow-50"
    },
    "success": {
      "base": "bg-green-500 dark:bg-green-600 focus-visible:outline-green-500 dark:focus-visible:outline-green-600",
      "label": "text-white dark:text-green-50",
      "icon": "!text-white dark:!text-green-50",
      "activityIndicator": "bg-white dark:bg-green-50"
    },
    "text": {
      "base": "bg-gray-900 dark:bg-gray-100 focus-visible:outline-gray-900 dark:focus-visible:outline-gray-100",
      "label": "text-gray-100 dark:text-gray-900",
      "icon": "!text-gray-100 dark:!text-gray-900",
      "activityIndicator": "bg-gray-100 dark:bg-gray-900"
    },
    "outline": {
      "base": "bg-gray-300 dark:bg-gray-700 focus-visible:outline-gray-300 dark:focus-visible:outline-gray-700",
      "label": "text-gray-900 dark:text-gray-100",
      "icon": "!text-gray-900 dark:!text-gray-100",
      "activityIndicator": "bg-gray-900 dark:bg-gray-100"
    },
    "backdrop": {
      "base": "bg-gray-900/50 dark:bg-gray-900/80 focus-visible:outline-gray-900/50 dark:focus-visible:outline-gray-900/80",
      "label": "text-white dark:text-white",
      "icon": "!text-white dark:!text-white",
      "activityIndicator": "bg-white dark:bg-white"
    }
  },
  "buttonOutline": {
    "primary": {
      "base": "group web:hover:bg-primary web:dark:hover:bg-dark-primary border-2 border-primary dark:border-dark-primary bg-transparent web:transition-[transform,color,background-color,border-color,text-decoration-color,fill,stroke]",
      "label": "web:hover:text-primary-foreground web:dark:hover:text-dark-primary-foreground web:group-hover:text-primary-foreground web:dark:group-hover:text-dark-primary-foreground text-primary dark:text-dark-primary",
      "icon": "web:hover:!text-primary-foreground web:dark:hover:!text-dark-primary-foreground web:group-hover:!text-primary-foreground web:dark:group-hover:!text-dark-primary-foreground !text-primary dark:!text-dark-primary",
      "activityIndicator": "web:hover:bg-primary-foreground web:dark:hover:bg-dark-primary-foreground web:group-hover:bg-primary-foreground web:dark:group-hover:bg-dark-primary-foreground bg-primary dark:bg-dark-primary"
    },
    "secondary": {
      "base": "group web:hover:bg-secondary web:dark:hover:bg-dark-secondary border-2 border-secondary dark:border-dark-secondary bg-transparent web:transition-[transform,color,background-color,border-color,text-decoration-color,fill,stroke]",
      "label": "web:hover:text-secondary-foreground web:dark:hover:text-dark-secondary-foreground web:group-hover:text-secondary-foreground web:dark:group-hover:text-dark-secondary-foreground text-secondary dark:text-dark-secondary",
      "icon": "web:hover:!text-secondary-foreground web:dark:hover:!text-dark-secondary-foreground web:group-hover:!text-secondary-foreground web:dark:group-hover:!text-dark-secondary-foreground !text-secondary dark:!text-dark-secondary",
      "activityIndicator": "web:hover:bg-secondary-foreground web:dark:hover:bg-dark-secondary-foreground web:group-hover:bg-secondary-foreground web:dark:group-hover:bg-dark-secondary-foreground bg-secondary dark:bg-dark-secondary"
    },
    "surface": {
      "base": "group web:hover:bg-gray-100 web:dark:hover:bg-gray-800 border-2 border-gray-100 dark:border-gray-800 bg-transparent web:transition-[transform,color,background-color,border-color,text-decoration-color,fill,stroke]",
      "label": "web:hover:text-gray-900 web:dark:hover:text-gray-100 web:group-hover:text-gray-900 web:dark:group-hover:text-gray-100 text-gray-100 dark:text-gray-800",
      "icon": "web:hover:!text-gray-900 web:dark:hover:!text-gray-100 web:group-hover:!text-gray-900 web:dark:group-hover:!text-gray-100 !text-gray-100 dark:!text-gray-800",
      "activityIndicator": "web:hover:bg-gray-100-foreground web:dark:hover:bg-gray-100 web:group-hover:bg-gray-900 web:dark:group-hover:bg-gray-100 bg-gray-100 dark:bg-gray-800"
    },
    "background": {
      "base": "group web:hover:bg-white web:dark:hover:bg-gray-900 border-2 border-white dark:border-gray-900 bg-transparent web:transition-[transform,color,background-color,border-color,text-decoration-color,fill,stroke]",
      "label": "web:hover:text-gray-900 web:dark:hover:text-gray-100 web:group-hover:text-gray-900 web:dark:group-hover:text-gray-100 text-white dark:text-gray-900",
      "icon": "web:hover:!text-gray-900 web:dark:hover:!text-gray-100 web:group-hover:!text-gray-900 web:dark:group-hover:!text-gray-100 !text-white dark:!text-gray-900",
      "activityIndicator": "web:hover:bg-white-foreground web:dark:hover:bg-gray-100 web:group-hover:bg-gray-900 web:dark:group-hover:bg-gray-100 bg-white dark:bg-gray-900"
    },
    "neutral": {
      "base": "group web:hover:bg-gray-500 web:dark:hover:bg-gray-600 border-2 border-gray-500 dark:border-gray-600 bg-transparent web:transition-[transform,color,background-color,border-color,text-decoration-color,fill,stroke]",
      "label": "web:hover:text-white web:dark:hover:text-gray-50 web:group-hover:text-white web:dark:group-hover:text-gray-50 text-gray-500 dark:text-gray-600",
      "icon": "web:hover:!text-white web:dark:hover:!text-gray-50 web:group-hover:!text-white web:dark:group-hover:!text-gray-50 !text-gray-500 dark:!text-gray-600",
      "activityIndicator": "web:hover:bg-gray-500-foreground web:dark:hover:bg-gray-50 web:group-hover:bg-white web:dark:group-hover:bg-gray-50 bg-gray-500 dark:bg-gray-600"
    },
    "error": {
      "base": "group web:hover:bg-red-500 web:dark:hover:bg-red-600 border-2 border-red-500 dark:border-red-600 bg-transparent web:transition-[transform,color,background-color,border-color,text-decoration-color,fill,stroke]",
      "label": "web:hover:text-white web:dark:hover:text-red-50 web:group-hover:text-white web:dark:group-hover:text-red-50 text-red-500 dark:text-red-600",
      "icon": "web:hover:!text-white web:dark:hover:!text-red-50 web:group-hover:!text-white web:dark:group-hover:!text-red-50 !text-red-500 dark:!text-red-600",
      "activityIndicator": "web:hover:bg-red-500-foreground web:dark:hover:bg-red-50 web:group-hover:bg-white web:dark:group-hover:bg-red-50 bg-red-500 dark:bg-red-600"
    },
    "info": {
      "base": "group web:hover:bg-blue-500 web:dark:hover:bg-blue-600 border-2 border-blue-500 dark:border-blue-600 bg-transparent web:transition-[transform,color,background-color,border-color,text-decoration-color,fill,stroke]",
      "label": "web:hover:text-white web:dark:hover:text-blue-50 web:group-hover:text-white web:dark:group-hover:text-blue-50 text-blue-500 dark:text-blue-600",
      "icon": "web:hover:!text-white web:dark:hover:!text-blue-50 web:group-hover:!text-white web:dark:group-hover:!text-blue-50 !text-blue-500 dark:!text-blue-600",
      "activityIndicator": "web:hover:bg-blue-500-foreground web:dark:hover:bg-blue-50 web:group-hover:bg-white web:dark:group-hover:bg-blue-50 bg-blue-500 dark:bg-blue-600"
    },
    "warning": {
      "base": "group web:hover:bg-yellow-500 web:dark:hover:bg-yellow-600 border-2 border-yellow-500 dark:border-yellow-600 bg-transparent web:transition-[transform,color,background-color,border-color,text-decoration-color,fill,stroke]",
      "label": "web:hover:text-yellow-900 web:dark:hover:text-yellow-50 web:group-hover:text-yellow-900 web:dark:group-hover:text-yellow-50 text-yellow-500 dark:text-yellow-600",
      "icon": "web:hover:!text-yellow-900 web:dark:hover:!text-yellow-50 web:group-hover:!text-yellow-900 web:dark:group-hover:!text-yellow-50 !text-yellow-500 dark:!text-yellow-600",
      "activityIndicator": "web:hover:bg-yellow-500-foreground web:dark:hover:bg-yellow-50 web:group-hover:bg-yellow-900 web:dark:group-hover:bg-yellow-50 bg-yellow-500 dark:bg-yellow-600"
    },
    "success": {
      "base": "group web:hover:bg-green-500 web:dark:hover:bg-green-600 border-2 border-green-500 dark:border-green-600 bg-transparent web:transition-[transform,color,background-color,border-color,text-decoration-color,fill,stroke]",
      "label": "web:hover:text-white web:dark:hover:text-green-50 web:group-hover:text-white web:dark:group-hover:text-green-50 text-green-500 dark:text-green-600",
      "icon": "web:hover:!text-white web:dark:hover:!text-green-50 web:group-hover:!text-white web:dark:group-hover:!text-green-50 !text-green-500 dark:!text-green-600",
      "activityIndicator": "web:hover:bg-green-500-foreground web:dark:hover:bg-green-50 web:group-hover:bg-white web:dark:group-hover:bg-green-50 bg-green-500 dark:bg-green-600"
    },
    "text": {
      "base": "group web:hover:bg-gray-900 web:dark:hover:bg-gray-100 border-2 border-gray-900 dark:border-gray-100 bg-transparent web:transition-[transform,color,background-color,border-color,text-decoration-color,fill,stroke]",
      "label": "web:hover:text-gray-100 web:dark:hover:text-gray-900 web:group-hover:text-gray-100 web:dark:group-hover:text-gray-900 text-gray-900 dark:text-gray-100",
      "icon": "web:hover:!text-gray-100 web:dark:hover:!text-gray-900 web:group-hover:!text-gray-100 web:dark:group-hover:!text-gray-900 !text-gray-900 dark:!text-gray-100",
      "activityIndicator": "web:hover:bg-gray-900-foreground web:dark:hover:bg-gray-900 web:group-hover:bg-gray-100 web:dark:group-hover:bg-gray-900 bg-gray-900 dark:bg-gray-100"
    },
    "outline": {
      "base": "group web:hover:bg-gray-300 web:dark:hover:bg-gray-700 border-2 border-gray-300 dark:border-gray-700 bg-transparent web:transition-[transform,color,background-color,border-color,text-decoration-color,fill,stroke]",
      "label": "web:hover:text-gray-900 web:dark:hover:text-gray-100 web:group-hover:text-gray-900 web:dark:group-hover:text-gray-100 text-gray-300 dark:text-gray-700",
      "icon": "web:hover:!text-gray-900 web:dark:hover:!text-gray-100 web:group-hover:!text-gray-900 web:dark:group-hover:!text-gray-100 !text-gray-300 dark:!text-gray-700",
      "activityIndicator": "web:hover:bg-gray-300-foreground web:dark:hover:bg-gray-100 web:group-hover:bg-gray-900 web:dark:group-hover:bg-gray-100 bg-gray-300 dark:bg-gray-700"
    },
    "backdrop": {
      "base": "group web:hover:bg-gray-900/50 web:dark:hover:bg-gray-900/80 border-2 border-gray-900/50 dark:border-gray-900/80 bg-transparent web:transition-[transform,color,background-color,border-color,text-decoration-color,fill,stroke]",
      "label": "web:hover:text-white web:dark:hover:text-white web:group-hover:text-white web:dark:group-hover:text-white text-gray-900/50 dark:text-gray-900/80",
      "icon": "web:hover:!text-white web:dark:hover:!text-white web:group-hover:!text-white web:dark:group-hover:!text-white !text-gray-900/50 dark:!text-gray-900/80",
      "activityIndicator": "web:hover:bg-gray-900/50-foreground web:dark:hover:bg-white web:group-hover:bg-white web:dark:group-hover:bg-white bg-gray-900/50 dark:bg-gray-900/80"
    }
  },
  "surface": {
    "primary": "bg-primary dark:bg-dark-primary text-primary-foreground dark:text-dark-primary-foreground",
    "secondary": "bg-secondary dark:bg-dark-secondary text-secondary-foreground dark:text-dark-secondary-foreground",
    "surface": "bg-gray-100 dark:bg-gray-800 text-gray-900 dark:text-gray-100",
    "background": "bg-white dark:bg-gray-900 text-gray-900 dark:text-gray-100",
    "neutral": "bg-gray-500 dark:bg-gray-600 text-white dark:text-gray-50",
    "error": "bg-red-500 dark:bg-red-600 text-white dark:text-red-50",
    "info": "bg-blue-500 dark:bg-blue-600 text-white dark:text-blue-50",
    "warning": "bg-yellow-500 dark:bg-yellow-600 text-yellow-900 dark:text-yellow-50",
    "success": "bg-green-500 dark:bg-green-600 text-white dark:text-green-50",
    "text": "bg-gray-900 dark:bg-gray-100 text-gray-100 dark:text-gray-900",
    "outline": "bg-gray-300 dark:bg-gray-700 text-gray-900 dark:text-gray-100",
    "backdrop": "bg-gray-900/50 dark:bg-gray-900/80 text-white dark:text-white"
  },
  "hoverBackground": {
    "primary": "hover:bg-primary dark:bg-dark-primary",
    "secondary": "hover:bg-secondary dark:bg-dark-secondary",
    "surface": "hover:bg-gray-100 dark:bg-gray-800",
    "background": "hover:bg-white dark:bg-gray-900",
    "neutral": "hover:bg-gray-500 dark:bg-gray-600",
    "error": "hover:bg-red-500 dark:bg-red-600",
    "info": "hover:bg-blue-500 dark:bg-blue-600",
    "warning": "hover:bg-yellow-500 dark:bg-yellow-600",
    "success": "hover:bg-green-500 dark:bg-green-600",
    "text": "hover:bg-gray-900 dark:bg-gray-100",
    "outline": "hover:bg-gray-300 dark:bg-gray-700",
    "backdrop": "hover:bg-gray-900/50 dark:bg-gray-900/80"
  },
  "activeBackground": {
    "primary": "active:bg-primary dark:active:bg-dark-primary",
    "secondary": "active:bg-secondary dark:active:bg-dark-secondary",
    "surface": "active:bg-gray-100 dark:active:bg-gray-800",
    "background": "active:bg-white dark:active:bg-gray-900",
    "neutral": "active:bg-gray-500 dark:active:bg-gray-600",
    "error": "active:bg-red-500 dark:active:bg-red-600",
    "info": "active:bg-blue-500 dark:active:bg-blue-600",
    "warning": "active:bg-yellow-500 dark:active:bg-yellow-600",
    "success": "active:bg-green-500 dark:active:bg-green-600",
    "text": "active:bg-gray-900 dark:active:bg-gray-100",
    "outline": "active:bg-gray-300 dark:active:bg-gray-700",
    "backdrop": "active:bg-gray-900/50 dark:active:bg-gray-900/80"
  },
  "shadow": {
    "primary": "shadow-primary dark:shadow-dark-primary",
    "secondary": "shadow-secondary dark:shadow-dark-secondary",
    "surface": "shadow-gray-100 dark:shadow-gray-800",
    "background": "shadow-white dark:shadow-gray-900",
    "neutral": "shadow-gray-500 dark:shadow-gray-600",
    "error": "shadow-red-500 dark:shadow-red-600",
    "info": "shadow-blue-500 dark:shadow-blue-600",
    "warning": "shadow-yellow-500 dark:shadow-yellow-600",
    "success": "shadow-green-500 dark:shadow-green-600",
    "text": "shadow-gray-900 dark:shadow-gray-100",
    "outline": "shadow-gray-300 dark:shadow-gray-700",
    "backdrop": "shadow-gray-900/50 dark:shadow-gray-900/80"
  },
  "hoverShadow": {
    "primary": "hover:shadow-primary dark:hover:shadow-dark-primary",
    "secondary": "hover:shadow-secondary dark:hover:shadow-dark-secondary",
    "surface": "hover:shadow-gray-100 dark:hover:shadow-gray-800",
    "background": "hover:shadow-white dark:hover:shadow-gray-900",
    "neutral": "hover:shadow-gray-500 dark:hover:shadow-gray-600",
    "error": "hover:shadow-red-500 dark:hover:shadow-red-600",
    "info": "hover:shadow-blue-500 dark:hover:shadow-blue-600",
    "warning": "hover:shadow-yellow-500 dark:hover:shadow-yellow-600",
    "success": "hover:shadow-green-500 dark:hover:shadow-green-600",
    "text": "hover:shadow-gray-900 dark:hover:shadow-gray-100",
    "outline": "hover:shadow-gray-300 dark:hover:shadow-gray-700",
    "backdrop": "hover:shadow-gray-900/50 dark:hover:shadow-gray-900/80"
  },
  "activeShadow": {
    "primary": "active:shadow-primary dark:active:shadow-dark-primary",
    "secondary": "active:shadow-secondary dark:active:shadow-dark-secondary",
    "surface": "active:shadow-gray-100 dark:active:shadow-gray-800",
    "background": "active:shadow-white dark:active:shadow-gray-900",
    "neutral": "active:shadow-gray-500 dark:active:shadow-gray-600",
    "error": "active:shadow-red-500 dark:active:shadow-red-600",
    "info": "active:shadow-blue-500 dark:active:shadow-blue-600",
    "warning": "active:shadow-yellow-500 dark:active:shadow-yellow-600",
    "success": "active:shadow-green-500 dark:active:shadow-green-600",
    "text": "active:shadow-gray-900 dark:active:shadow-gray-100",
    "outline": "active:shadow-gray-300 dark:active:shadow-gray-700",
    "backdrop": "active:shadow-gray-900/50 dark:active:shadow-gray-900/80"
  },
  "hoverText": {
    "primary": "hover:text-primary dark:hover:text-dark-primary",
    "secondary": "hover:text-secondary dark:hover:text-dark-secondary",
    "surface": "hover:text-gray-100 dark:hover:text-gray-800",
    "background": "hover:text-white dark:hover:text-gray-900",
    "neutral": "hover:text-gray-500 dark:hover:text-gray-600",
    "error": "hover:text-red-500 dark:hover:text-red-600",
    "info": "hover:text-blue-500 dark:hover:text-blue-600",
    "warning": "hover:text-yellow-500 dark:hover:text-yellow-600",
    "success": "hover:text-green-500 dark:hover:text-green-600",
    "text": "hover:text-gray-900 dark:hover:text-gray-100",
    "outline": "hover:text-gray-300 dark:hover:text-gray-700",
    "backdrop": "hover:text-gray-900/50 dark:hover:text-gray-900/80",
    "primary-foreground": "hover:text-primary-foreground dark:hover:text-dark-primary-foreground",
    "secondary-foreground": "hover:text-secondary-foreground dark:hover:text-dark-secondary-foreground",
    "surface-foreground": "hover:text-gray-900 dark:hover:text-gray-100",
    "background-foreground": "hover:text-gray-900 dark:hover:text-gray-100",
    "neutral-foreground": "hover:text-white dark:hover:text-gray-50",
    "error-foreground": "hover:text-white dark:hover:text-red-50",
    "info-foreground": "hover:text-white dark:hover:text-blue-50",
    "warning-foreground": "hover:text-yellow-900 dark:hover:text-yellow-50",
    "success-foreground": "hover:text-white dark:hover:text-green-50",
    "text-foreground": "hover:text-gray-100 dark:hover:text-gray-900",
    "outline-foreground": "hover:text-gray-900 dark:hover:text-gray-100",
    "backdrop-foreground": "hover:text-white dark:hover:text-white"
  },
  "activeText": {
    "primary": "active:text-primary dark:active:text-dark-primary",
    "secondary": "active:text-secondary dark:active:text-dark-secondary",
    "surface": "active:text-gray-100 dark:active:text-gray-800",
    "background": "active:text-white dark:active:text-gray-900",
    "neutral": "active:text-gray-500 dark:active:text-gray-600",
    "error": "active:text-red-500 dark:active:text-red-600",
    "info": "active:text-blue-500 dark:active:text-blue-600",
    "warning": "active:text-yellow-500 dark:active:text-yellow-600",
    "success": "active:text-green-500 dark:active:text-green-600",
    "text": "active:text-gray-900 dark:active:text-gray-100",
    "outline": "active:text-gray-300 dark:active:text-gray-700",
    "backdrop": "active:text-gray-900/50 dark:active:text-gray-900/80",
    "primary-foreground": "active:text-primary-foreground dark:active:text-dark-primary-foreground",
    "secondary-foreground": "active:text-secondary-foreground dark:active:text-dark-secondary-foreground",
    "surface-foreground": "active:text-gray-900 dark:active:text-gray-100",
    "background-foreground": "active:text-gray-900 dark:active:text-gray-100",
    "neutral-foreground": "active:text-white dark:active:text-gray-50",
    "error-foreground": "active:text-white dark:active:text-red-50",
    "info-foreground": "active:text-white dark:active:text-blue-50",
    "warning-foreground": "active:text-yellow-900 dark:active:text-yellow-50",
    "success-foreground": "active:text-white dark:active:text-green-50",
    "text-foreground": "active:text-gray-100 dark:active:text-gray-900",
    "outline-foreground": "active:text-gray-900 dark:active:text-gray-100",
    "backdrop-foreground": "active:text-white dark:active:text-white"
  },
  "text": {
    "primary": "text-primary dark:text-dark-primary",
    "secondary": "text-secondary dark:text-dark-secondary",
    "surface": "text-gray-100 dark:text-gray-800",
    "background": "text-white dark:text-gray-900",
    "neutral": "text-gray-500 dark:text-gray-600",
    "error": "text-red-500 dark:text-red-600",
    "info": "text-blue-500 dark:text-blue-600",
    "warning": "text-yellow-500 dark:text-yellow-600",
    "success": "text-green-500 dark:text-green-600",
    "text": "text-gray-900 dark:text-gray-100",
    "outline": "text-gray-300 dark:text-gray-700",
    "backdrop": "text-gray-900/50 dark:text-gray-900/80",
    "primary-foreground": "text-primary-foreground dark:text-dark-primary-foreground",
    "secondary-foreground": "text-secondary-foreground dark:text-dark-secondary-foreground",
    "surface-foreground": "text-gray-900 dark:text-gray-100",
    "background-foreground": "text-gray-900 dark:text-gray-100",
    "neutral-foreground": "text-white dark:text-gray-50",
    "error-foreground": "text-white dark:text-red-50",
    "info-foreground": "text-white dark:text-blue-50",
    "warning-foreground": "text-yellow-900 dark:text-yellow-50",
    "success-foreground": "text-white dark:text-green-50",
    "text-foreground": "text-gray-100 dark:text-gray-900",
    "outline-foreground": "text-gray-900 dark:text-gray-100",
    "backdrop-foreground": "text-white dark:text-white"
  },
  "textDecoration": {
    "primary": "decoration-primary dark:decoration-dark-primary",
    "secondary": "decoration-secondary dark:decoration-dark-secondary",
    "surface": "decoration-gray-100 dark:decoration-gray-800",
    "background": "decoration-white dark:decoration-gray-900",
    "neutral": "decoration-gray-500 dark:decoration-gray-600",
    "error": "decoration-red-500 dark:decoration-red-600",
    "info": "decoration-blue-500 dark:decoration-blue-600",
    "warning": "decoration-yellow-500 dark:decoration-yellow-600",
    "success": "decoration-green-500 dark:decoration-green-600",
    "text": "decoration-gray-900 dark:decoration-gray-100",
    "outline": "decoration-gray-300 dark:decoration-gray-700",
    "backdrop": "decoration-gray-900/50 dark:decoration-gray-900/80",
    "primary-foreground": "decoration-primary-foreground dark:decoration-dark-primary-foreground",
    "secondary-foreground": "decoration-secondary-foreground dark:decoration-dark-secondary-foreground",
    "surface-foreground": "decoration-gray-900 dark:decoration-gray-100",
    "background-foreground": "decoration-gray-900 dark:decoration-gray-100",
    "neutral-foreground": "decoration-white dark:decoration-gray-50",
    "error-foreground": "decoration-white dark:decoration-red-50",
    "info-foreground": "decoration-white dark:decoration-blue-50",
    "warning-foreground": "decoration-yellow-900 dark:decoration-yellow-50",
    "success-foreground": "decoration-white dark:decoration-green-50",
    "text-foreground": "decoration-gray-100 dark:decoration-gray-900",
    "outline-foreground": "decoration-gray-900 dark:decoration-gray-100",
    "backdrop-foreground": "decoration-white dark:decoration-white"
  },
  "icon": {
    "primary": "!text-primary dark:!text-dark-primary",
    "secondary": "!text-secondary dark:!text-dark-secondary",
    "surface": "!text-gray-100 dark:!text-gray-800",
    "background": "!text-white dark:!text-gray-900",
    "neutral": "!text-gray-500 dark:!text-gray-600",
    "error": "!text-red-500 dark:!text-red-600",
    "info": "!text-blue-500 dark:!text-blue-600",
    "warning": "!text-yellow-500 dark:!text-yellow-600",
    "success": "!text-green-500 dark:!text-green-600",
    "text": "!text-gray-900 dark:!text-gray-100",
    "outline": "!text-gray-300 dark:!text-gray-700",
    "backdrop": "!text-gray-900/50 dark:!text-gray-900/80",
    "primary-foreground": "!text-primary-foreground dark:!text-dark-primary-foreground",
    "secondary-foreground": "!text-secondary-foreground dark:!text-dark-secondary-foreground",
    "surface-foreground": "!text-gray-900 dark:!text-gray-100",
    "background-foreground": "!text-gray-900 dark:!text-gray-100",
    "neutral-foreground": "!text-white dark:!text-gray-50",
    "error-foreground": "!text-white dark:!text-red-50",
    "info-foreground": "!text-white dark:!text-blue-50",
    "warning-foreground": "!text-yellow-900 dark:!text-yellow-50",
    "success-foreground": "!text-white dark:!text-green-50",
    "text-foreground": "!text-gray-100 dark:!text-gray-900",
    "outline-foreground": "!text-gray-900 dark:!text-gray-100",
    "backdrop-foreground": "!text-white dark:!text-white"
  },
  "hoverIcon": {
    "primary": "hover:!text-primary dark:hover:!text-dark-primary",
    "secondary": "hover:!text-secondary dark:hover:!text-dark-secondary",
    "surface": "hover:!text-gray-100 dark:hover:!text-gray-800",
    "background": "hover:!text-white dark:hover:!text-gray-900",
    "neutral": "hover:!text-gray-500 dark:hover:!text-gray-600",
    "error": "hover:!text-red-500 dark:hover:!text-red-600",
    "info": "hover:!text-blue-500 dark:hover:!text-blue-600",
    "warning": "hover:!text-yellow-500 dark:hover:!text-yellow-600",
    "success": "hover:!text-green-500 dark:hover:!text-green-600",
    "text": "hover:!text-gray-900 dark:hover:!text-gray-100",
    "outline": "hover:!text-gray-300 dark:hover:!text-gray-700",
    "backdrop": "hover:!text-gray-900/50 dark:hover:!text-gray-900/80",
    "primary-foreground": "hover:!text-primary-foreground dark:hover:!text-dark-primary-foreground",
    "secondary-foreground": "hover:!text-secondary-foreground dark:hover:!text-dark-secondary-foreground",
    "surface-foreground": "hover:!text-gray-900 dark:hover:!text-gray-100",
    "background-foreground": "hover:!text-gray-900 dark:hover:!text-gray-100",
    "neutral-foreground": "hover:!text-white dark:hover:!text-gray-50",
    "error-foreground": "hover:!text-white dark:hover:!text-red-50",
    "info-foreground": "hover:!text-white dark:hover:!text-blue-50",
    "warning-foreground": "hover:!text-yellow-900 dark:hover:!text-yellow-50",
    "success-foreground": "hover:!text-white dark:hover:!text-green-50",
    "text-foreground": "hover:!text-gray-100 dark:hover:!text-gray-900",
    "outline-foreground": "hover:!text-gray-900 dark:hover:!text-gray-100",
    "backdrop-foreground": "hover:!text-white dark:hover:!text-white"
  },
  "activeIcon": {
    "primary": "active:!text-primary dark:active:!text-dark-primary",
    "secondary": "active:!text-secondary dark:active:!text-dark-secondary",
    "surface": "active:!text-gray-100 dark:active:!text-gray-800",
    "background": "active:!text-white dark:active:!text-gray-900",
    "neutral": "active:!text-gray-500 dark:active:!text-gray-600",
    "error": "active:!text-red-500 dark:active:!text-red-600",
    "info": "active:!text-blue-500 dark:active:!text-blue-600",
    "warning": "active:!text-yellow-500 dark:active:!text-yellow-600",
    "success": "active:!text-green-500 dark:active:!text-green-600",
    "text": "active:!text-gray-900 dark:active:!text-gray-100",
    "outline": "active:!text-gray-300 dark:active:!text-gray-700",
    "backdrop": "active:!text-gray-900/50 dark:active:!text-gray-900/80",
    "primary-foreground": "active:!text-primary-foreground dark:active:!text-dark-primary-foreground",
    "secondary-foreground": "active:!text-secondary-foreground dark:active:!text-dark-secondary-foreground",
    "surface-foreground": "active:!text-gray-900 dark:active:!text-gray-100",
    "background-foreground": "active:!text-gray-900 dark:active:!text-gray-100",
    "neutral-foreground": "active:!text-white dark:active:!text-gray-50",
    "error-foreground": "active:!text-white dark:active:!text-red-50",
    "info-foreground": "active:!text-white dark:active:!text-blue-50",
    "warning-foreground": "active:!text-yellow-900 dark:active:!text-yellow-50",
    "success-foreground": "active:!text-white dark:active:!text-green-50",
    "text-foreground": "active:!text-gray-100 dark:active:!text-gray-900",
    "outline-foreground": "active:!text-gray-900 dark:active:!text-gray-100",
    "backdrop-foreground": "active:!text-white dark:active:!text-white"
  },
  "background": {
    "primary": "bg-primary dark:bg-dark-primary",
    "secondary": "bg-secondary dark:bg-dark-secondary",
    "surface": "bg-gray-100 dark:bg-gray-800",
    "background": "bg-white dark:bg-gray-900",
    "neutral": "bg-gray-500 dark:bg-gray-600",
    "error": "bg-red-500 dark:bg-red-600",
    "info": "bg-blue-500 dark:bg-blue-600",
    "warning": "bg-yellow-500 dark:bg-yellow-600",
    "success": "bg-green-500 dark:bg-green-600",
    "text": "bg-gray-900 dark:bg-gray-100",
    "outline": "bg-gray-300 dark:bg-gray-700",
    "backdrop": "bg-gray-900/50 dark:bg-gray-900/80"
  },
  "textForeground": {
    "primary-foreground": "text-primary-foreground dark:text-dark-primary-foreground",
    "secondary-foreground": "text-secondary-foreground dark:text-dark-secondary-foreground",
    "surface-foreground": "text-gray-900 dark:text-gray-100",
    "background-foreground": "text-gray-900 dark:text-gray-100",
    "neutral-foreground": "text-white dark:text-gray-50",
    "error-foreground": "text-white dark:text-red-50",
    "info-foreground": "text-white dark:text-blue-50",
    "warning-foreground": "text-yellow-900 dark:text-yellow-50",
    "success-foreground": "text-white dark:text-green-50",
    "text-foreground": "text-gray-100 dark:text-gray-900",
    "outline-foreground": "text-gray-900 dark:text-gray-100",
    "backdrop-foreground": "text-white dark:text-white"
  },
  "hoverTextForeground": {
    "primary-foreground": "hover:text-primary-foreground dark:hover:text-dark-primary-foreground",
    "secondary-foreground": "hover:text-secondary-foreground dark:hover:text-dark-secondary-foreground",
    "surface-foreground": "hover:text-gray-900 dark:hover:text-gray-100",
    "background-foreground": "hover:text-gray-900 dark:hover:text-gray-100",
    "neutral-foreground": "hover:text-white dark:hover:text-gray-50",
    "error-foreground": "hover:text-white dark:hover:text-red-50",
    "info-foreground": "hover:text-white dark:hover:text-blue-50",
    "warning-foreground": "hover:text-yellow-900 dark:hover:text-yellow-50",
    "success-foreground": "hover:text-white dark:hover:text-green-50",
    "text-foreground": "hover:text-gray-100 dark:hover:text-gray-900",
    "outline-foreground": "hover:text-gray-900 dark:hover:text-gray-100",
    "backdrop-foreground": "hover:text-white dark:hover:text-white"
  },
  "activeTextForeground": {
    "primary-foreground": "active:text-primary-foreground dark:active:text-dark-primary-foreground",
    "secondary-foreground": "active:text-secondary-foreground dark:active:text-dark-secondary-foreground",
    "surface-foreground": "active:text-gray-900 dark:active:text-gray-100",
    "background-foreground": "active:text-gray-900 dark:active:text-gray-100",
    "neutral-foreground": "active:text-white dark:active:text-gray-50",
    "error-foreground": "active:text-white dark:active:text-red-50",
    "info-foreground": "active:text-white dark:active:text-blue-50",
    "warning-foreground": "active:text-yellow-900 dark:active:text-yellow-50",
    "success-foreground": "active:text-white dark:active:text-green-50",
    "text-foreground": "active:text-gray-100 dark:active:text-gray-900",
    "outline-foreground": "active:text-gray-900 dark:active:text-gray-100",
    "backdrop-foreground": "active:text-white dark:active:text-white"
  },
  "iconForeground": {
    "primary-foreground": "!text-primary-foreground dark:!text-dark-primary-foreground",
    "secondary-foreground": "!text-secondary-foreground dark:!text-dark-secondary-foreground",
    "surface-foreground": "!text-gray-900 dark:!text-gray-100",
    "background-foreground": "!text-gray-900 dark:!text-gray-100",
    "neutral-foreground": "!text-white dark:!text-gray-50",
    "error-foreground": "!text-white dark:!text-red-50",
    "info-foreground": "!text-white dark:!text-blue-50",
    "warning-foreground": "!text-yellow-900 dark:!text-yellow-50",
    "success-foreground": "!text-white dark:!text-green-50",
    "text-foreground": "!text-gray-100 dark:!text-gray-900",
    "outline-foreground": "!text-gray-900 dark:!text-gray-100",
    "backdrop-foreground": "!text-white dark:!text-white"
  },
  "hoverIconForeground": {
    "primary-foreground": "hover:!text-primary-foreground dark:hover:!text-dark-primary-foreground",
    "secondary-foreground": "hover:!text-secondary-foreground dark:hover:!text-dark-secondary-foreground",
    "surface-foreground": "hover:!text-gray-900 dark:hover:!text-gray-100",
    "background-foreground": "hover:!text-gray-900 dark:hover:!text-gray-100",
    "neutral-foreground": "hover:!text-white dark:hover:!text-gray-50",
    "error-foreground": "hover:!text-white dark:hover:!text-red-50",
    "info-foreground": "hover:!text-white dark:hover:!text-blue-50",
    "warning-foreground": "hover:!text-yellow-900 dark:hover:!text-yellow-50",
    "success-foreground": "hover:!text-white dark:hover:!text-green-50",
    "text-foreground": "hover:!text-gray-100 dark:hover:!text-gray-900",
    "outline-foreground": "hover:!text-gray-900 dark:hover:!text-gray-100",
    "backdrop-foreground": "hover:!text-white dark:hover:!text-white"
  },
  "activeIconForeground": {
    "primary-foreground": "active:!text-primary-foreground dark:active:!text-dark-primary-foreground",
    "secondary-foreground": "active:!text-secondary-foreground dark:active:!text-dark-secondary-foreground",
    "surface-foreground": "active:!text-gray-900 dark:active:!text-gray-100",
    "background-foreground": "active:!text-gray-900 dark:active:!text-gray-100",
    "neutral-foreground": "active:!text-white dark:active:!text-gray-50",
    "error-foreground": "active:!text-white dark:active:!text-red-50",
    "info-foreground": "active:!text-white dark:active:!text-blue-50",
    "warning-foreground": "active:!text-yellow-900 dark:active:!text-yellow-50",
    "success-foreground": "active:!text-white dark:active:!text-green-50",
    "text-foreground": "active:!text-gray-100 dark:active:!text-gray-900",
    "outline-foreground": "active:!text-gray-900 dark:active:!text-gray-100",
    "backdrop-foreground": "active:!text-white dark:active:!text-white"
  },
  "outlineColor": {
    "primary": "outline-primary dark:outline-dark-primary",
    "secondary": "outline-secondary dark:outline-dark-secondary",
    "surface": "outline-gray-100 dark:outline-gray-800",
    "background": "outline-white dark:outline-gray-900",
    "neutral": "outline-gray-500 dark:outline-gray-600",
    "error": "outline-red-500 dark:outline-red-600",
    "info": "outline-blue-500 dark:outline-blue-600",
    "warning": "outline-yellow-500 dark:outline-yellow-600",
    "success": "outline-green-500 dark:outline-green-600",
    "text": "outline-gray-900 dark:outline-gray-100",
    "outline": "outline-gray-300 dark:outline-gray-700",
    "backdrop": "outline-gray-900/50 dark:outline-gray-900/80",
    "primary-foreground": "outline-primary-foreground dark:outline-dark-primary-foreground",
    "secondary-foreground": "outline-secondary-foreground dark:outline-dark-secondary-foreground",
    "surface-foreground": "outline-gray-900 dark:outline-gray-100",
    "background-foreground": "outline-gray-900 dark:outline-gray-100",
    "neutral-foreground": "outline-white dark:outline-gray-50",
    "error-foreground": "outline-white dark:outline-red-50",
    "info-foreground": "outline-white dark:outline-blue-50",
    "warning-foreground": "outline-yellow-900 dark:outline-yellow-50",
    "success-foreground": "outline-white dark:outline-green-50",
    "text-foreground": "outline-gray-100 dark:outline-gray-900",
    "outline-foreground": "outline-gray-900 dark:outline-gray-100",
    "backdrop-foreground": "outline-white dark:outline-white"
  },
  "hoverOutlineColor": {
    "primary": "hover:outline-primary dark:hover:outline-dark-primary",
    "secondary": "hover:outline-secondary dark:hover:outline-dark-secondary",
    "surface": "hover:outline-gray-100 dark:hover:outline-gray-800",
    "background": "hover:outline-white dark:hover:outline-gray-900",
    "neutral": "hover:outline-gray-500 dark:hover:outline-gray-600",
    "error": "hover:outline-red-500 dark:hover:outline-red-600",
    "info": "hover:outline-blue-500 dark:hover:outline-blue-600",
    "warning": "hover:outline-yellow-500 dark:hover:outline-yellow-600",
    "success": "hover:outline-green-500 dark:hover:outline-green-600",
    "text": "hover:outline-gray-900 dark:hover:outline-gray-100",
    "outline": "hover:outline-gray-300 dark:hover:outline-gray-700",
    "backdrop": "hover:outline-gray-900/50 dark:hover:outline-gray-900/80",
    "primary-foreground": "hover:outline-primary-foreground dark:hover:outline-dark-primary-foreground",
    "secondary-foreground": "hover:outline-secondary-foreground dark:hover:outline-dark-secondary-foreground",
    "surface-foreground": "hover:outline-gray-900 dark:hover:outline-gray-100",
    "background-foreground": "hover:outline-gray-900 dark:hover:outline-gray-100",
    "neutral-foreground": "hover:outline-white dark:hover:outline-gray-50",
    "error-foreground": "hover:outline-white dark:hover:outline-red-50",
    "info-foreground": "hover:outline-white dark:hover:outline-blue-50",
    "warning-foreground": "hover:outline-yellow-900 dark:hover:outline-yellow-50",
    "success-foreground": "hover:outline-white dark:hover:outline-green-50",
    "text-foreground": "hover:outline-gray-100 dark:hover:outline-gray-900",
    "outline-foreground": "hover:outline-gray-900 dark:hover:outline-gray-100",
    "backdrop-foreground": "hover:outline-white dark:hover:outline-white"
  },
  "activeOutlineColor": {
    "primary": "active:outline-primary dark:active:outline-dark-primary",
    "secondary": "active:outline-secondary dark:active:outline-dark-secondary",
    "surface": "active:outline-gray-100 dark:active:outline-gray-800",
    "background": "active:outline-white dark:active:outline-gray-900",
    "neutral": "active:outline-gray-500 dark:active:outline-gray-600",
    "error": "active:outline-red-500 dark:active:outline-red-600",
    "info": "active:outline-blue-500 dark:active:outline-blue-600",
    "warning": "active:outline-yellow-500 dark:active:outline-yellow-600",
    "success": "active:outline-green-500 dark:active:outline-green-600",
    "text": "active:outline-gray-900 dark:active:outline-gray-100",
    "outline": "active:outline-gray-300 dark:active:outline-gray-700",
    "backdrop": "active:outline-gray-900/50 dark:active:outline-gray-900/80",
    "primary-foreground": "active:outline-primary-foreground dark:active:outline-dark-primary-foreground",
    "secondary-foreground": "active:outline-secondary-foreground dark:active:outline-dark-secondary-foreground",
    "surface-foreground": "active:outline-gray-900 dark:active:outline-gray-100",
    "background-foreground": "active:outline-gray-900 dark:active:outline-gray-100",
    "neutral-foreground": "active:outline-white dark:active:outline-gray-50",
    "error-foreground": "active:outline-white dark:active:outline-red-50",
    "info-foreground": "active:outline-white dark:active:outline-blue-50",
    "warning-foreground": "active:outline-yellow-900 dark:active:outline-yellow-50",
    "success-foreground": "active:outline-white dark:active:outline-green-50",
    "text-foreground": "active:outline-gray-100 dark:active:outline-gray-900",
    "outline-foreground": "active:outline-gray-900 dark:active:outline-gray-100",
    "backdrop-foreground": "active:outline-white dark:active:outline-white"
  },
  "borderColor": {
    "primary": "border-primary dark:border-dark-primary",
    "secondary": "border-secondary dark:border-dark-secondary",
    "surface": "border-gray-100 dark:border-gray-800",
    "background": "border-white dark:border-gray-900",
    "neutral": "border-gray-500 dark:border-gray-600",
    "error": "border-red-500 dark:border-red-600",
    "info": "border-blue-500 dark:border-blue-600",
    "warning": "border-yellow-500 dark:border-yellow-600",
    "success": "border-green-500 dark:border-green-600",
    "text": "border-gray-900 dark:border-gray-100",
    "outline": "border-gray-300 dark:border-gray-700",
    "backdrop": "border-gray-900/50 dark:border-gray-900/80",
    "primary-foreground": "border-primary-foreground dark:border-dark-primary-foreground",
    "secondary-foreground": "border-secondary-foreground dark:border-dark-secondary-foreground",
    "surface-foreground": "border-gray-900 dark:border-gray-100",
    "background-foreground": "border-gray-900 dark:border-gray-100",
    "neutral-foreground": "border-white dark:border-gray-50",
    "error-foreground": "border-white dark:border-red-50",
    "info-foreground": "border-white dark:border-blue-50",
    "warning-foreground": "border-yellow-900 dark:border-yellow-50",
    "success-foreground": "border-white dark:border-green-50",
    "text-foreground": "border-gray-100 dark:border-gray-900",
    "outline-foreground": "border-gray-900 dark:border-gray-100",
    "backdrop-foreground": "border-white dark:border-white"
  },
  "hoverBorderColor": {
    "primary": "hover:border-primary dark:hover:border-dark-primary",
    "secondary": "hover:border-secondary dark:hover:border-dark-secondary",
    "surface": "hover:border-gray-100 dark:hover:border-gray-800",
    "background": "hover:border-white dark:hover:border-gray-900",
    "neutral": "hover:border-gray-500 dark:hover:border-gray-600",
    "error": "hover:border-red-500 dark:hover:border-red-600",
    "info": "hover:border-blue-500 dark:hover:border-blue-600",
    "warning": "hover:border-yellow-500 dark:hover:border-yellow-600",
    "success": "hover:border-green-500 dark:hover:border-green-600",
    "text": "hover:border-gray-900 dark:hover:border-gray-100",
    "outline": "hover:border-gray-300 dark:hover:border-gray-700",
    "backdrop": "hover:border-gray-900/50 dark:hover:border-gray-900/80",
    "primary-foreground": "hover:border-primary-foreground dark:hover:border-dark-primary-foreground",
    "secondary-foreground": "hover:border-secondary-foreground dark:hover:border-dark-secondary-foreground",
    "surface-foreground": "hover:border-gray-900 dark:hover:border-gray-100",
    "background-foreground": "hover:border-gray-900 dark:hover:border-gray-100",
    "neutral-foreground": "hover:border-white dark:hover:border-gray-50",
    "error-foreground": "hover:border-white dark:hover:border-red-50",
    "info-foreground": "hover:border-white dark:hover:border-blue-50",
    "warning-foreground": "hover:border-yellow-900 dark:hover:border-yellow-50",
    "success-foreground": "hover:border-white dark:hover:border-green-50",
    "text-foreground": "hover:border-gray-100 dark:hover:border-gray-900",
    "outline-foreground": "hover:border-gray-900 dark:hover:border-gray-100",
    "backdrop-foreground": "hover:border-white dark:hover:border-white"
  },
  "activeBorderColor": {
    "primary": "active:border-primary dark:active:border-dark-primary",
    "secondary": "active:border-secondary dark:active:border-dark-secondary",
    "surface": "active:border-gray-100 dark:active:border-gray-800",
    "background": "active:border-white dark:active:border-gray-900",
    "neutral": "active:border-gray-500 dark:active:border-gray-600",
    "error": "active:border-red-500 dark:active:border-red-600",
    "info": "active:border-blue-500 dark:active:border-blue-600",
    "warning": "active:border-yellow-500 dark:active:border-yellow-600",
    "success": "active:border-green-500 dark:active:border-green-600",
    "text": "active:border-gray-900 dark:active:border-gray-100",
    "outline": "active:border-gray-300 dark:active:border-gray-700",
    "backdrop": "active:border-gray-900/50 dark:active:border-gray-900/80",
    "primary-foreground": "active:border-primary-foreground dark:active:border-dark-primary-foreground",
    "secondary-foreground": "active:border-secondary-foreground dark:active:border-dark-secondary-foreground",
    "surface-foreground": "active:border-gray-900 dark:active:border-gray-100",
    "background-foreground": "active:border-gray-900 dark:active:border-gray-100",
    "neutral-foreground": "active:border-white dark:active:border-gray-50",
    "error-foreground": "active:border-white dark:active:border-red-50",
    "info-foreground": "active:border-white dark:active:border-blue-50",
    "warning-foreground": "active:border-yellow-900 dark:active:border-yellow-50",
    "success-foreground": "active:border-white dark:active:border-green-50",
    "text-foreground": "active:border-gray-100 dark:active:border-gray-900",
    "outline-foreground": "active:border-gray-900 dark:active:border-gray-100",
    "backdrop-foreground": "active:border-white dark:active:border-white"
  },
  "borderTopColor": {
    "primary": "border-t-primary dark:border-t-dark-primary",
    "secondary": "border-t-secondary dark:border-t-dark-secondary",
    "surface": "border-t-gray-100 dark:border-t-gray-800",
    "background": "border-t-white dark:border-t-gray-900",
    "neutral": "border-t-gray-500 dark:border-t-gray-600",
    "error": "border-t-red-500 dark:border-t-red-600",
    "info": "border-t-blue-500 dark:border-t-blue-600",
    "warning": "border-t-yellow-500 dark:border-t-yellow-600",
    "success": "border-t-green-500 dark:border-t-green-600",
    "text": "border-t-gray-900 dark:border-t-gray-100",
    "outline": "border-t-gray-300 dark:border-t-gray-700",
    "backdrop": "border-t-gray-900/50 dark:border-t-gray-900/80",
    "primary-foreground": "border-t-primary-foreground dark:border-t-dark-primary-foreground",
    "secondary-foreground": "border-t-secondary-foreground dark:border-t-dark-secondary-foreground",
    "surface-foreground": "border-t-gray-900 dark:border-t-gray-100",
    "background-foreground": "border-t-gray-900 dark:border-t-gray-100",
    "neutral-foreground": "border-t-white dark:border-t-gray-50",
    "error-foreground": "border-t-white dark:border-t-red-50",
    "info-foreground": "border-t-white dark:border-t-blue-50",
    "warning-foreground": "border-t-yellow-900 dark:border-t-yellow-50",
    "success-foreground": "border-t-white dark:border-t-green-50",
    "text-foreground": "border-t-gray-100 dark:border-t-gray-900",
    "outline-foreground": "border-t-gray-900 dark:border-t-gray-100",
    "backdrop-foreground": "border-t-white dark:border-t-white"
  },
  "borderBottomColor": {
    "primary": "border-b-primary dark:border-b-dark-primary",
    "secondary": "border-b-secondary dark:border-b-dark-secondary",
    "surface": "border-b-gray-100 dark:border-b-gray-800",
    "background": "border-b-white dark:border-b-gray-900",
    "neutral": "border-b-gray-500 dark:border-b-gray-600",
    "error": "border-b-red-500 dark:border-b-red-600",
    "info": "border-b-blue-500 dark:border-b-blue-600",
    "warning": "border-b-yellow-500 dark:border-b-yellow-600",
    "success": "border-b-green-500 dark:border-b-green-600",
    "text": "border-b-gray-900 dark:border-b-gray-100",
    "outline": "border-b-gray-300 dark:border-b-gray-700",
    "backdrop": "border-b-gray-900/50 dark:border-b-gray-900/80",
    "primary-foreground": "border-b-primary-foreground dark:border-b-dark-primary-foreground",
    "secondary-foreground": "border-b-secondary-foreground dark:border-b-dark-secondary-foreground",
    "surface-foreground": "border-b-gray-900 dark:border-b-gray-100",
    "background-foreground": "border-b-gray-900 dark:border-b-gray-100",
    "neutral-foreground": "border-b-white dark:border-b-gray-50",
    "error-foreground": "border-b-white dark:border-b-red-50",
    "info-foreground": "border-b-white dark:border-b-blue-50",
    "warning-foreground": "border-b-yellow-900 dark:border-b-yellow-50",
    "success-foreground": "border-b-white dark:border-b-green-50",
    "text-foreground": "border-b-gray-100 dark:border-b-gray-900",
    "outline-foreground": "border-b-gray-900 dark:border-b-gray-100",
    "backdrop-foreground": "border-b-white dark:border-b-white"
  },
  "borderLeftColor": {
    "primary": "border-l-primary dark:border-l-dark-primary",
    "secondary": "border-l-secondary dark:border-l-dark-secondary",
    "surface": "border-l-gray-100 dark:border-l-gray-800",
    "background": "border-l-white dark:border-l-gray-900",
    "neutral": "border-l-gray-500 dark:border-l-gray-600",
    "error": "border-l-red-500 dark:border-l-red-600",
    "info": "border-l-blue-500 dark:border-l-blue-600",
    "warning": "border-l-yellow-500 dark:border-l-yellow-600",
    "success": "border-l-green-500 dark:border-l-green-600",
    "text": "border-l-gray-900 dark:border-l-gray-100",
    "outline": "border-l-gray-300 dark:border-l-gray-700",
    "backdrop": "border-l-gray-900/50 dark:border-l-gray-900/80",
    "primary-foreground": "border-l-primary-foreground dark:border-l-dark-primary-foreground",
    "secondary-foreground": "border-l-secondary-foreground dark:border-l-dark-secondary-foreground",
    "surface-foreground": "border-l-gray-900 dark:border-l-gray-100",
    "background-foreground": "border-l-gray-900 dark:border-l-gray-100",
    "neutral-foreground": "border-l-white dark:border-l-gray-50",
    "error-foreground": "border-l-white dark:border-l-red-50",
    "info-foreground": "border-l-white dark:border-l-blue-50",
    "warning-foreground": "border-l-yellow-900 dark:border-l-yellow-50",
    "success-foreground": "border-l-white dark:border-l-green-50",
    "text-foreground": "border-l-gray-100 dark:border-l-gray-900",
    "outline-foreground": "border-l-gray-900 dark:border-l-gray-100",
    "backdrop-foreground": "border-l-white dark:border-l-white"
  },
  "borderRightColor": {
    "primary": "border-r-primary dark:border-r-dark-primary",
    "secondary": "border-r-secondary dark:border-r-dark-secondary",
    "surface": "border-r-gray-100 dark:border-r-gray-800",
    "background": "border-r-white dark:border-r-gray-900",
    "neutral": "border-r-gray-500 dark:border-r-gray-600",
    "error": "border-r-red-500 dark:border-r-red-600",
    "info": "border-r-blue-500 dark:border-r-blue-600",
    "warning": "border-r-yellow-500 dark:border-r-yellow-600",
    "success": "border-r-green-500 dark:border-r-green-600",
    "text": "border-r-gray-900 dark:border-r-gray-100",
    "outline": "border-r-gray-300 dark:border-r-gray-700",
    "backdrop": "border-r-gray-900/50 dark:border-r-gray-900/80",
    "primary-foreground": "border-r-primary-foreground dark:border-r-dark-primary-foreground",
    "secondary-foreground": "border-r-secondary-foreground dark:border-r-dark-secondary-foreground",
    "surface-foreground": "border-r-gray-900 dark:border-r-gray-100",
    "background-foreground": "border-r-gray-900 dark:border-r-gray-100",
    "neutral-foreground": "border-r-white dark:border-r-gray-50",
    "error-foreground": "border-r-white dark:border-r-red-50",
    "info-foreground": "border-r-white dark:border-r-blue-50",
    "warning-foreground": "border-r-yellow-900 dark:border-r-yellow-50",
    "success-foreground": "border-r-white dark:border-r-green-50",
    "text-foreground": "border-r-gray-100 dark:border-r-gray-900",
    "outline-foreground": "border-r-gray-900 dark:border-r-gray-100",
    "backdrop-foreground": "border-r-white dark:border-r-white"
  },
  "activityIndicator": {
    "primary": "bg-primary dark:bg-dark-primary",
    "secondary": "bg-secondary dark:bg-dark-secondary",
    "surface": "bg-gray-100 dark:bg-gray-800",
    "background": "bg-white dark:bg-gray-900",
    "neutral": "bg-gray-500 dark:bg-gray-600",
    "error": "bg-red-500 dark:bg-red-600",
    "info": "bg-blue-500 dark:bg-blue-600",
    "warning": "bg-yellow-500 dark:bg-yellow-600",
    "success": "bg-green-500 dark:bg-green-600",
    "text": "bg-gray-900 dark:bg-gray-100",
    "outline": "bg-gray-300 dark:bg-gray-700",
    "backdrop": "bg-gray-900/50 dark:bg-gray-900/80",
    "primary-foreground": "bg-primary-foreground dark:bg-dark-primary-foreground",
    "secondary-foreground": "bg-secondary-foreground dark:bg-dark-secondary-foreground",
    "surface-foreground": "bg-gray-900 dark:bg-gray-100",
    "background-foreground": "bg-gray-900 dark:bg-gray-100",
    "neutral-foreground": "bg-white dark:bg-gray-50",
    "error-foreground": "bg-white dark:bg-red-50",
    "info-foreground": "bg-white dark:bg-blue-50",
    "warning-foreground": "bg-yellow-900 dark:bg-yellow-50",
    "success-foreground": "bg-white dark:bg-green-50",
    "text-foreground": "bg-gray-100 dark:bg-gray-900",
    "outline-foreground": "bg-gray-900 dark:bg-gray-100",
    "backdrop-foreground": "bg-white dark:bg-white"
  },
  "ringColors": {
    "primary": "ring-primary dark:ring-dark-primary",
    "secondary": "ring-secondary dark:ring-dark-secondary",
    "surface": "ring-gray-100 dark:ring-gray-800",
    "background": "ring-white dark:ring-gray-900",
    "neutral": "ring-gray-500 dark:ring-gray-600",
    "error": "ring-red-500 dark:ring-red-600",
    "info": "ring-blue-500 dark:ring-blue-600",
    "warning": "ring-yellow-500 dark:ring-yellow-600",
    "success": "ring-green-500 dark:ring-green-600",
    "text": "ring-gray-900 dark:ring-gray-100",
    "outline": "ring-gray-300 dark:ring-gray-700",
    "backdrop": "ring-gray-900/50 dark:ring-gray-900/80",
    "primary-foreground": "ring-primary-foreground dark:ring-dark-primary-foreground",
    "secondary-foreground": "ring-secondary-foreground dark:ring-dark-secondary-foreground",
    "surface-foreground": "ring-gray-900 dark:ring-gray-100",
    "background-foreground": "ring-gray-900 dark:ring-gray-100",
    "neutral-foreground": "ring-white dark:ring-gray-50",
    "error-foreground": "ring-white dark:ring-red-50",
    "info-foreground": "ring-white dark:ring-blue-50",
    "warning-foreground": "ring-yellow-900 dark:ring-yellow-50",
    "success-foreground": "ring-white dark:ring-green-50",
    "text-foreground": "ring-gray-100 dark:ring-gray-900",
    "outline-foreground": "ring-gray-900 dark:ring-gray-100",
    "backdrop-foreground": "ring-white dark:ring-white"
  },
  "hoverRingColors": {
    "primary": "hover:ring-primary dark:hover:ring-dark-primary",
    "secondary": "hover:ring-secondary dark:hover:ring-dark-secondary",
    "surface": "hover:ring-gray-100 dark:hover:ring-gray-800",
    "background": "hover:ring-white dark:hover:ring-gray-900",
    "neutral": "hover:ring-gray-500 dark:hover:ring-gray-600",
    "error": "hover:ring-red-500 dark:hover:ring-red-600",
    "info": "hover:ring-blue-500 dark:hover:ring-blue-600",
    "warning": "hover:ring-yellow-500 dark:hover:ring-yellow-600",
    "success": "hover:ring-green-500 dark:hover:ring-green-600",
    "text": "hover:ring-gray-900 dark:hover:ring-gray-100",
    "outline": "hover:ring-gray-300 dark:hover:ring-gray-700",
    "backdrop": "hover:ring-gray-900/50 dark:hover:ring-gray-900/80",
    "primary-foreground": "hover:ring-primary-foreground dark:hover:ring-dark-primary-foreground",
    "secondary-foreground": "hover:ring-secondary-foreground dark:hover:ring-dark-secondary-foreground",
    "surface-foreground": "hover:ring-gray-900 dark:hover:ring-gray-100",
    "background-foreground": "hover:ring-gray-900 dark:hover:ring-gray-100",
    "neutral-foreground": "hover:ring-white dark:hover:ring-gray-50",
    "error-foreground": "hover:ring-white dark:hover:ring-red-50",
    "info-foreground": "hover:ring-white dark:hover:ring-blue-50",
    "warning-foreground": "hover:ring-yellow-900 dark:hover:ring-yellow-50",
    "success-foreground": "hover:ring-white dark:hover:ring-green-50",
    "text-foreground": "hover:ring-gray-100 dark:hover:ring-gray-900",
    "outline-foreground": "hover:ring-gray-900 dark:hover:ring-gray-100",
    "backdrop-foreground": "hover:ring-white dark:hover:ring-white"
  },
  "activeRingColors": {
    "primary": "active:ring-primary dark:active:ring-dark-primary",
    "secondary": "active:ring-secondary dark:active:ring-dark-secondary",
    "surface": "active:ring-gray-100 dark:active:ring-gray-800",
    "background": "active:ring-white dark:active:ring-gray-900",
    "neutral": "active:ring-gray-500 dark:active:ring-gray-600",
    "error": "active:ring-red-500 dark:active:ring-red-600",
    "info": "active:ring-blue-500 dark:active:ring-blue-600",
    "warning": "active:ring-yellow-500 dark:active:ring-yellow-600",
    "success": "active:ring-green-500 dark:active:ring-green-600",
    "text": "active:ring-gray-900 dark:active:ring-gray-100",
    "outline": "active:ring-gray-300 dark:active:ring-gray-700",
    "backdrop": "active:ring-gray-900/50 dark:active:ring-gray-900/80",
    "primary-foreground": "active:ring-primary-foreground dark:active:ring-dark-primary-foreground",
    "secondary-foreground": "active:ring-secondary-foreground dark:active:ring-dark-secondary-foreground",
    "surface-foreground": "active:ring-gray-900 dark:active:ring-gray-100",
    "background-foreground": "active:ring-gray-900 dark:active:ring-gray-100",
    "neutral-foreground": "active:ring-white dark:active:ring-gray-50",
    "error-foreground": "active:ring-white dark:active:ring-red-50",
    "info-foreground": "active:ring-white dark:active:ring-blue-50",
    "warning-foreground": "active:ring-yellow-900 dark:active:ring-yellow-50",
    "success-foreground": "active:ring-white dark:active:ring-green-50",
    "text-foreground": "active:ring-gray-100 dark:active:ring-gray-900",
    "outline-foreground": "active:ring-gray-900 dark:active:ring-gray-100",
    "backdrop-foreground": "active:ring-white dark:active:ring-white"
  },
  "focusRingColors": {
    "primary": "focus:ring-primary dark:focus:ring-dark-primary",
    "secondary": "focus:ring-secondary dark:focus:ring-dark-secondary",
    "surface": "focus:ring-gray-100 dark:focus:ring-gray-800",
    "background": "focus:ring-white dark:focus:ring-gray-900",
    "neutral": "focus:ring-gray-500 dark:focus:ring-gray-600",
    "error": "focus:ring-red-500 dark:focus:ring-red-600",
    "info": "focus:ring-blue-500 dark:focus:ring-blue-600",
    "warning": "focus:ring-yellow-500 dark:focus:ring-yellow-600",
    "success": "focus:ring-green-500 dark:focus:ring-green-600",
    "text": "focus:ring-gray-900 dark:focus:ring-gray-100",
    "outline": "focus:ring-gray-300 dark:focus:ring-gray-700",
    "backdrop": "focus:ring-gray-900/50 dark:focus:ring-gray-900/80",
    "primary-foreground": "focus:ring-primary-foreground dark:focus:ring-dark-primary-foreground",
    "secondary-foreground": "focus:ring-secondary-foreground dark:focus:ring-dark-secondary-foreground",
    "surface-foreground": "focus:ring-gray-900 dark:focus:ring-gray-100",
    "background-foreground": "focus:ring-gray-900 dark:focus:ring-gray-100",
    "neutral-foreground": "focus:ring-white dark:focus:ring-gray-50",
    "error-foreground": "focus:ring-white dark:focus:ring-red-50",
    "info-foreground": "focus:ring-white dark:focus:ring-blue-50",
    "warning-foreground": "focus:ring-yellow-900 dark:focus:ring-yellow-50",
    "success-foreground": "focus:ring-white dark:focus:ring-green-50",
    "text-foreground": "focus:ring-gray-100 dark:focus:ring-gray-900",
    "outline-foreground": "focus:ring-gray-900 dark:focus:ring-gray-100",
    "backdrop-foreground": "focus:ring-white dark:focus:ring-white"
  },
  "fillColor": {
    "primary": "fill-primary dark:fill-dark-primary",
    "secondary": "fill-secondary dark:fill-dark-secondary",
    "surface": "fill-gray-100 dark:fill-gray-800",
    "background": "fill-white dark:fill-gray-900",
    "neutral": "fill-gray-500 dark:fill-gray-600",
    "error": "fill-red-500 dark:fill-red-600",
    "info": "fill-blue-500 dark:fill-blue-600",
    "warning": "fill-yellow-500 dark:fill-yellow-600",
    "success": "fill-green-500 dark:fill-green-600",
    "text": "fill-gray-900 dark:fill-gray-100",
    "outline": "fill-gray-300 dark:fill-gray-700",
    "backdrop": "fill-gray-900/50 dark:fill-gray-900/80",
    "primary-foreground": "fill-primary-foreground dark:fill-dark-primary-foreground",
    "secondary-foreground": "fill-secondary-foreground dark:fill-dark-secondary-foreground",
    "surface-foreground": "fill-gray-900 dark:fill-gray-100",
    "background-foreground": "fill-gray-900 dark:fill-gray-100",
    "neutral-foreground": "fill-white dark:fill-gray-50",
    "error-foreground": "fill-white dark:fill-red-50",
    "info-foreground": "fill-white dark:fill-blue-50",
    "warning-foreground": "fill-yellow-900 dark:fill-yellow-50",
    "success-foreground": "fill-white dark:fill-green-50",
    "text-foreground": "fill-gray-100 dark:fill-gray-900",
    "outline-foreground": "fill-gray-900 dark:fill-gray-100",
    "backdrop-foreground": "fill-white dark:fill-white"
  },
  "allColors": {}
}
    