import "./globals.css";
import "./fonts.css"
import { AppRoot } from "@resk/nativewind";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={``}>
        <AppRoot className="bg-background">
          {children}
        </AppRoot>
      </body>
    </html>
  );
}
